PokemonMansion_1F_Text_TedIntro::
    .string "¿Y tú quién eres?\n"
    .string "Aquí no debería haber nadie.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "¡Auh!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "¿Una llave? ¡Ni idea de lo que me\n"
    .string "estás hablando!$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "¡Aaaaaaaaaah! ¡Qué susto!\n"
    .string "¡Pensaba que eras un fantasma!$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "¡Uf, no hay forma de que gane!$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Yo estaba aquí tranquilamente\n"
    .string "curioseando un poco, pero creo\l"
    .string "que voy a irme.\p"
    .string "Tengo un poco de miedo.$"


PokemonMansion_1F_Text_FullMewSighting1::
    .string "Un sonido suave recorre la mansión...\p"
    .string "Por un instante, una pequeña silueta\n"
    .string "rosada cruza el pasillo y desaparece.$"
