gFameCheckerFlavorText_ProfOak0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LABORATORIO POKéMON del PROF. OAK$"

gFameCheckerFlavorText_ProfOak1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quería hacer una guía de todos\n"
	.string "los POKéMON del mundo...\p"
	.string "¡Era mi sueño!$"

gFameCheckerFlavorText_ProfOak2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El PROF. OAK es un experto\n"
	.string "en POKéMON!\p"
	.string "¡Es admirado por muchos de los\n"
	.string "ENTRENADORES POKéMON!$"

gFameCheckerFlavorText_ProfOak3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según dicen, el PROF. OAK vive\n"
	.string "con su nieta DALIA y {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He oído que OAK te tiene\n"
	.string "mucha admiración, criatura.\p"
	.string "Ese carcamal era fuerte y guapote,\n"
	.string "pero ya hace mucho de eso.\p"
	.string "Han pasado muchos años, sí.\n"
	.string "Es la sombra de lo que fue.$"

gFameCheckerFlavorText_ProfOak5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}El PROF. OAK va a tener pronto\n"
	.string "su propio programa de radio.\p"
	.string "Será el SEMINARIO sobre POKéMON\n"
	.string "del PROF. OAK.$"

gFameCheckerFlavorText_Daisy0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si le enseñas a DALIA tus POKéMON,\n"
	.string "sabrá decirte si les gustas o no.\p"
	.string "Y puede que les dé un lavado de\n"
	.string "cara para que estén presentables.$"

gFameCheckerFlavorText_Daisy1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pero los POKéMON a quien más\n"
	.string "quieren es a DALIA, creo.$"

gFameCheckerFlavorText_Daisy2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La chiquilla cuidaba con mimo a un\n"
	.string "POKéMON. Era un angelito, la cría.\p"
	.string "Lo que no recuerdo es el nombre...\n"
	.string "Bueno, creo que era DALIA.$"

gFameCheckerFlavorText_Daisy3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según dicen, el PROF. OAK vive\n"
	.string "con su nieta DALIA y {RIVAL}.$"

gFameCheckerFlavorText_Daisy4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Es que allí hay una chica, DALIA,\n"
	.string "que toma TÉ a diario.\p"
	.string "Suele comprarlo en el CENTRO\n"
	.string "COMERCIAL de AZULONA.$"

gFameCheckerFlavorText_Daisy5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡La campeona de la edición de\n"
	.string "primavera del CONCURSO POKéMON\l"
	.string "es DALIA OAK, de PUEBLO PALETA!$"

gFameCheckerFlavorText_Brock0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de PLATEADA: BROCK\l"
	.string "¡Es fuerte como una roca!$"

gFameCheckerFlavorText_Brock1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Creo en la gran resistencia de la\n"
	.string "roca y en la determinación!\p"
	.string "¡Por eso todos mis POKéMON son\n"
	.string "del tipo ROCA!$"

gFameCheckerFlavorText_Brock2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡No hay muchos ENTRENADORES\n"
	.string "de POKéMON por aquí!\p"
	.string "¡Todos parecen CAZABICHOS, salvo\n"
	.string "BROCK, del GIMNASIO de PLATEADA!$"

gFameCheckerFlavorText_Brock3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK es, además de fuerte, guay.\n"
	.string "Todos lo respetan y admiran mucho.\p"
	.string "Yo quiero ser LÍDER de GIMNASIO\n"
	.string "como él.$"

gFameCheckerFlavorText_Brock4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Estoy buscando fósiles en las\n"
	.string "entrañas del MT. MOON.\p"
	.string "A veces me ayuda BROCK,\n"
	.string "del GIMNASIO de PLATEADA.$"

gFameCheckerFlavorText_Brock5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, BROCK\n"
	.string "casi nunca se ríe, ¡pero una vez\l"
	.string "que empieza, no para!$"

gFameCheckerFlavorText_Misty0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de CELESTE: MISTY\l"
	.string "¡La sirena distorsionada!$"

gFameCheckerFlavorText_Misty1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Mi táctica es la ofensiva total\n"
	.string "con los POKéMON del tipo AGUA!$"

gFameCheckerFlavorText_Misty2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡MISTY es cada vez más fuerte!\p"
	.string "¡No perderá con alguien como tú!$"

gFameCheckerFlavorText_Misty3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Por aquí hay muchos ENTRENADORES\n"
	.string "fuertes y POKéMON del tipo AGUA.\p"
	.string "Dicen que MISTY, del GIMNASIO\n"
	.string "de CELESTE, se entrena por aquí.$"

gFameCheckerFlavorText_Misty4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En este cabo queda mucha gente.\p"
	.string "MISTY, la LÍDER del GIMNASIO,\n"
	.string "suele venir por aquí.$"

gFameCheckerFlavorText_Misty5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, MISTY\n"
	.string "adora a PRIMA, del ALTO MANDO.$"

gFameCheckerFlavorText_LtSurge0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de CARMÍN: LT. SURGE\l"
	.string "¡El Rayo americano!$"

gFameCheckerFlavorText_LtSurge1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Los POKéMON ELÉCTRICOS\n"
	.string "me salvaron en combate!$"

gFameCheckerFlavorText_LtSurge2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Cuando estaba en el ejército,\n"
	.string "el LT. SURGE era muy estricto!$"

gFameCheckerFlavorText_LtSurge3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El LT. SURGE siempre fue muy\n"
	.string "cuidadoso en el ejército!$"

gFameCheckerFlavorText_LtSurge4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE colocó cerraduras\n"
	.string "dobles en el GIMNASIO.\p"
	.string "¡Las puso por todos sitios!$"

gFameCheckerFlavorText_LtSurge5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, LT. SURGE\n"
	.string "era piloto cuando vivía en Estados\l"
	.string "Unidos.\p"
	.string "Y se valía de la electricidad\n"
	.string "generada por sus POKéMON\l"
	.string "para poner en marcha su avión.$"

gFameCheckerFlavorText_Erika0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de AZULONA: ERIKA\l"
	.string "¡Princesa amante de la Naturaleza!$"

gFameCheckerFlavorText_Erika1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Enseño el arte de las flores.\n"
	.string "Mis POKéMON son del tipo PLANTA.$"

gFameCheckerFlavorText_Erika2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡ERIKA, nuestra LÍDER, puede\n"
	.string "parecer muy tranquila, pero es muy\l"
	.string "hábil!$"

gFameCheckerFlavorText_Erika3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡En nuestro GIMNASIO sólo luchamos\n"
	.string "con POKéMON del tipo PLANTA!\p"
	.string "¡Y también los usamos para hacer\n"
	.string "adornos florales!$"

gFameCheckerFlavorText_Erika4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}No coleccionaría POKéMON si\n"
	.string "fueran feos.$"

gFameCheckerFlavorText_Erika5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, es fácil\n"
	.string "ver a ERIKA echándose una siesta\l"
	.string "en el GIMNASIO de AZULONA.$"

gFameCheckerFlavorText_Koga0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de FUCSIA: KOGA\l"
	.string "El venenoso maestro ninja.$"

gFameCheckerFlavorText_Koga1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Adoro a mis temidos POKéMON\n"
	.string "del tipo VENENO!$"

gFameCheckerFlavorText_Koga2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Seguiré entrenándome con KOGA,\n"
	.string "mi maestro ninja!$"

gFameCheckerFlavorText_Koga3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mi padre es el LÍDER del GIMNASIO\n"
	.string "de este pueblo.\p"
	.string "Yo me estoy entrenando para usar\n"
	.string "POKéMON del tipo VENENO igual\l"
	.string "que hace mi padre.$"

gFameCheckerFlavorText_Koga4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, KOGA\n"
	.string "tiene grandes conocimientos\l"
	.string "de medicina.\p"
	.string "Incluso elabora las medicinas\n"
	.string "que sus POKéMON necesitan.$"

gFameCheckerFlavorText_Koga5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La ZONA del SAFARI es gigante,\n"
	.string "¿no te parece?\p"
	.string "El LÍDER del GIMNASIO de FUCSIA,\n"
	.string "KOGA, viene con mucha frecuencia\l"
	.string "por aquí.\p"
	.string "Gracias a él, podemos jugar aquí\n"
	.string "sin miedo.$"

gFameCheckerFlavorText_Sabrina0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de AZAFRÁN: SABRINA\l"
	.string "¡Genio de los POKéMON PSÍQUICOS!$"

gFameCheckerFlavorText_Sabrina1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Sabes algo de la LÍDER del\n"
	.string "GIMNASIO de AZAFRÁN?\p"
	.string "Usa POKéMON del tipo PSÍQUICO,\n"
	.string "¿no?$"

gFameCheckerFlavorText_Sabrina2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Tengo poderes psíquicos desde\n"
	.string "que era niña!\p"
	.string "Primero aprendí a doblar cucharas\n"
	.string "con la mente.$"

gFameCheckerFlavorText_Sabrina3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Odio luchar, pero si quieres\n"
	.string "puedo enseñarte mis poderes!$"

gFameCheckerFlavorText_Sabrina4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, SABRINA\n"
	.string "se comunica en combate con sus\l"
	.string "POKéMON, sin necesidad de hablar.$"

gFameCheckerFlavorText_Sabrina5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡SABRINA ganó al MAESTRO de\n"
	.string "KARATE de la puerta de al lado!$"

gFameCheckerFlavorText_Blaine0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de CANELA: BLAINE\l"
	.string "¡El maestro de los acertijos!$"

gFameCheckerFlavorText_Blaine1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Mis feroces POKéMON de FUEGO\n"
	.string "quemarán a quien me desafíe!$"

gFameCheckerFlavorText_Blaine2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE se perdió en la montaña,\n"
	.string "y se hizo de noche...\p"
	.string "¡Pero apareció un feroz pájaro\n"
	.string "POKéMON...!\p"
	.string "¡E iluminó el camino a BLAINE\n"
	.string "para que pudiera bajar!$"

gFameCheckerFlavorText_Blaine3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE, del GIMNASIO CANELA,\n"
	.string "es un hombre raro que lleva años\l"
	.string "viviendo aquí.\p"
	.string "Antes de que construyeran el\n"
	.string "LABORATORIO, ya vivía aquí.$"

gFameCheckerFlavorText_Blaine4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Y esto?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Una foto de BLAINE\n"
	.string "y el SR. FUJI...\p"
	.string "Aparecen juntos con una sonrisa\n"
	.string "de oreja a oreja.$"

gFameCheckerFlavorText_Blaine5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, BLAINE\n"
	.string "sólo se quita las gafas de sol\l"
	.string "cuando contesta a preguntas.$"

gFameCheckerFlavorText_Lorelei0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Yo soy PRIMA, del ALTO MANDO!$"

gFameCheckerFlavorText_Lorelei1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Nadie me supera con los POKéMON\n"
	.string "que congelan!$"

gFameCheckerFlavorText_Lorelei2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En esta isla nació y creció una\n"
	.string "ENTRENADORA fuerte y poderosa\l"
	.string "como pocas.\p"
	.string "Seguro que la conoces, se llama\n"
	.string "PRIMA y es del ALTO MANDO.$"

gFameCheckerFlavorText_Lorelei3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Lo que sí se conoce de ella es\n"
	.string "su estilo de lucha elegante, único\l"
	.string "y calculador.$"

gFameCheckerFlavorText_Lorelei4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Sabías que PRIMA tiene un\n"
	.string "montón de muñecos de peluche?\p"
	.string "¡Cada vez que vuelve a ISLA\n"
	.string "QUARTA, aumenta la colección!$"

gFameCheckerFlavorText_Lorelei5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Creo que el LAPRAS que tiene,\n"
	.string "es el mismo que atrapó de pequeña.\p"
	.string "Yo creo que se hizo con él\n"
	.string "en la CUEVA GLACIADA...\p"
	.string "Me parece que lo tiene desde\n"
	.string "entonces.$"

gFameCheckerFlavorText_Bruno0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Yo soy BRUNO, del ALTO MANDO!$"

gFameCheckerFlavorText_Bruno1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Siempre he vivido con mis POKéMON\n"
	.string "del tipo LUCHA y los he entrenado\l"
	.string "yo mismo!$"

gFameCheckerFlavorText_Bruno2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, BRUNO\n"
	.string "se unió al ALTO MANDO para luchar\l"
	.string "contra los mejores ENTRENADORES.$"

gFameCheckerFlavorText_Bruno3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, ejemplo al que sigo, viene\n"
	.string "al BALNEARIO cada vez que puede.\p"
	.string "No sólo para recuperarse él,\n"
	.string "también lo hace por sus POKéMON.$"

gFameCheckerFlavorText_Bruno4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Era uno de los miembros del ALTO\n"
	.string "MANDO. Se llamaba BRUNO.\p"
	.string "Pero se fue decepcionado cuando\n"
	.string "vio que no quedaban bastones de\l"
	.string "caramelo superfuertes.$"

gFameCheckerFlavorText_Bruno5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Fíjate en BRUNO...\n"
	.string "Él se entrenó con un tal MARCIAL.$"

gFameCheckerFlavorText_Agatha0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Yo soy AGATHA, del ALTO MANDO!$"

gFameCheckerFlavorText_Agatha1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Los POKéMON del tipo FANTASMA\n"
	.string "de AGATHA son escalofriantemente\l"
	.string "fuertes.$"

gFameCheckerFlavorText_Agatha2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Además ¡no sabes el genio que\n"
	.string "tiene la señora!\p"
	.string "¡Como empiece a gritar, lo llevas\n"
	.string "claro!$"

gFameCheckerFlavorText_Agatha3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, AGATHA\n"
	.string "y el PROF. OAK estuvieron\p"
	.string "enfrentados durante su formación\n"
	.string "como ENTRENADORES.$"

gFameCheckerFlavorText_Agatha4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He oído que OAK te tiene\n"
	.string "mucha admiración, criatura.\p"
	.string "Ese carcamal era fuerte y guapote,\n"
	.string "pero ya hace mucho de eso.\p"
	.string "Han pasado muchos años, sí.\n"
	.string "Es la sombra de lo que fue.$"

gFameCheckerFlavorText_Agatha5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mira a AGATHA, por ejemplo.\p"
	.string "Es el miembro de más edad\n"
	.string "del ALTO MANDO.$"

gFameCheckerFlavorText_Lance0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Dirijo al ALTO MANDO!\p"
	.string "¡Puedes llamarme LANCE,\n"
	.string "el ENTRENADOR de dragones!$"

gFameCheckerFlavorText_Lance1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Los dragones son míticos POKéMON!\p"
	.string "¡Son difíciles de capturar y\n"
	.string "entrenar, pero sus poderes son\l"
	.string "muy superiores!\p"
	.string "¡Son casi invencibles!$"

gFameCheckerFlavorText_Lance2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Es justo!\n"
	.string "¡Es admirado!\l"
	.string "¡Todos quieren estar a su lado!$"

gFameCheckerFlavorText_Lance3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tenemos un cliente habitual, LANCE,\n"
	.string "que suele comprar capas.\p"
	.string "La verdad es que debe de tener\n"
	.string "un montón iguales en su casa...$"

gFameCheckerFlavorText_Lance4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, quien fundó\n"
	.string "el clan de los maestros del tipo\l"
	.string "DRAGÓN fue el abuelo de LANCE.$"

gFameCheckerFlavorText_Lance5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Por lo que sé, un primo de LANCE\n"
	.string "es también LÍDER de un GIMNASIO\l"
	.string "de por ahí.$"

gFameCheckerFlavorText_Bill0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Él fue también el que inventó el\n"
	.string "Sistema de Almacenamiento de\l"
	.string "POKéMON para PC!$"

gFameCheckerFlavorText_Bill1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡BILL tiene muchísimos POKéMON!\n"
	.string "¡Y algunos son muy raros!$"

gFameCheckerFlavorText_Bill2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Es mi nieto!\p"
	.string "¡Le gustaba coleccionar cosas\n"
	.string "desde niño!$"

gFameCheckerFlavorText_Bill3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL es un POKéMANÍACO,\n"
	.string "a él le gustan todos.\p"
	.string "Creo que el primero que atrapó\n"
	.string "fue un ABRA.$"

gFameCheckerFlavorText_Bill4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL es de CIUDAD TRIGAL,\n"
	.string "donde aún viven sus amigos.\p"
	.string "Dicen que es una ciudad muy\n"
	.string "alegre y animada.$"

gFameCheckerFlavorText_Bill5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Creo que BILL no tolera muy bien\n"
	.string "la leche. Le da dolor de estómago.$"

gFameCheckerFlavorText_MrFuji0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Es muy amable!\p"
	.string "¡Cuida de los POKéMON huérfanos\n"
	.string "y abandonados!$"

gFameCheckerFlavorText_MrFuji1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}El tipo, que ya tiene unos años,\n"
	.string "se plantó en nuestra GUARIDA.\p"
	.string "Y empezó a decir que estábamos\n"
	.string "haciendo daño a los POKéMON.\p"
	.string "¡La cosa es para tomársela\n"
	.string "en serio!$"

gFameCheckerFlavorText_MrFuji2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}REVISTA POKéMON\n"
	.string "¡Gran concurso mensual de dibujo\l"
	.string "POKéMON!\p"
	.string "El formulario de inscripción está\n"
	.string "en...\p"
	.string "¡Anda, se lo han llevado!\n"
	.string "¡Se ha debido de inscribir alguien!$"

gFameCheckerFlavorText_MrFuji3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He oído que el SR. FUJI tampoco\n"
	.string "es de por aquí.$"

gFameCheckerFlavorText_MrFuji4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Y esto?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Una foto de BLAINE\n"
	.string "y el SR. FUJI...\p"
	.string "Aparecen juntos con una sonrisa\n"
	.string "de oreja a oreja.$"

gFameCheckerFlavorText_MrFuji5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nota del editor: el tímido\n"
	.string "SR. FUJI no ha querido contestar\l"
	.string "a nuestras preguntas.\p"
	.string "Con todo, hay que decir que es una\n"
	.string "persona muy querida en PUEBLO\l"
	.string "LAVANDA.$"

gFameCheckerFlavorText_Giovanni0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El TEAM ROCKET necesita los\n"
	.string "POKéMON para financiar sus\l"
	.string "malvados planes!\p"
	.string "¡Yo soy GIOVANNI, su líder!$"

gFameCheckerFlavorText_Giovanni1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Los tipejos esos que se apoderaron\n"
	.string "de nuestro edificio...\p"
	.string "Su JEFE dijo que estaba buscando\n"
	.string "POKéMON fuertes.$"

gFameCheckerFlavorText_Giovanni2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El JEFE del TEAM ROCKET es muy\n"
	.string "cruel!\p"
	.string "Sólo quiere a los POKéMON para\n"
	.string "luchar.$"

gFameCheckerFlavorText_Giovanni3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Ésta es mi guarida!\p"
	.string "¡Quería volver a formar al TEAM\n"
	.string "ROCKET desde aquí!$"

gFameCheckerFlavorText_Giovanni4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Qué dices? ¿Que GIOVANNI era\n"
	.string "el LÍDER del GIMNASIO?$"

gFameCheckerFlavorText_Giovanni5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tú... tú no eres el retoño\n"
	.string "de GIOVANNI, ¿verdad?\p"
	.string "No, no puede ser, el retoño\n"
	.string "de GIOVANNI es pelirrojo.$"


gFameCheckerPersonName_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario del PROF. OAK\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Sabes por qué luchan y compiten\n"
	.string "tanto por ti los POKéMON?\p"
	.string "Porque ven el cariño que tienes\n"
	.string "hacia los POKéMON y lo que confías\l"
	.string "en ellos.\p"
	.string "Tenlo siempre en cuenta.$"

gFameCheckerPersonName_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DALIA$"

gFameCheckerPersonQuote_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de DALIA para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mientras hacía una pausa para\n"
	.string "tomar té, he visto que te has\l"
	.string "vuelto muy fuerte y hábil.\p"
	.string "Espero que sigas siendo la persona\n"
	.string "ideal para luchar contra mi\l"
	.string "hermano pequeño.$"

gFameCheckerPersonName_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BROCK para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En este mundo nuestro tan grande,\n"
	.string "hacen falta fuertes ENTRENADORES.\p"
	.string "¡Debemos seguir entrenándonos\n"
	.string "para ser cada vez más fuertes!$"

gFameCheckerPersonName_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de MISTY para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Voy a seguir entrenándome aquí\n"
	.string "en el GIMNASIO.\p"
	.string "Cuando perfeccione mi técnica,\n"
	.string "me iré a viajar por ahí.$"

gFameCheckerPersonName_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de LT. SURGE\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Eh, personaje!\n"
	.string "¡Me quedé molido tras el combate!\p"
	.string "No pensé que hubiera ENTRENADORES\n"
	.string "tan valientes como tú.\p"
	.string "Conseguiste que cambiara mi opinión\n"
	.string "sobre ti.$"

gFameCheckerPersonName_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de ERIKA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Estoy encantada de que haya\n"
	.string "ENTRENADORES fuertes como tú.\p"
	.string "Me motiva y me ayuda a superarme\n"
	.string "a mí misma.\p"
	.string "Espero verte de nuevo.\n"
	.string "Zzz...$"

gFameCheckerPersonName_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de KOGA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tú y yo deberíamos exigirnos\n"
	.string "más y entrenarnos con empeño para\l"
	.string "cumplir lo que nos propongamos.\p"
	.string "Bueno, voy a entrenar a mi hija.$"

gFameCheckerPersonName_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de SABRINA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}El cariño que les tienes a tus\n"
	.string "POKéMON...\p"
	.string "Tuvo más fuerza que mis poderes\n"
	.string "psíquicos.$"

gFameCheckerPersonName_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BLAINE\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Mis POKéMON de fuego van\n"
	.string "a alcanzar una fuerza increíble!\p"
	.string "A ver, una pregunta: ¿cuántos\n"
	.string "POKéMON del tipo FUEGO hay?$"

gFameCheckerPersonName_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PRIMA$"

gFameCheckerPersonQuote_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de PRIMA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Estoy muy agradecida por tu ayuda.\p"
	.string "¡Pero no te confíes, en combate\n"
	.string "no pienso pasarte ni una!$"

gFameCheckerPersonName_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BRUNO\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He aprendido mucho de la fuerza\n"
	.string "que tenéis tú y tus POKéMON...\p"
	.string "¡La próxima vez seré yo quien\n"
	.string "te enseñe a ti!$"

gFameCheckerPersonName_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de AGATHA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Espero que no te vuelvas como\n"
	.string "el blandengue de OAK con los años.\p"
	.string "¡Sigue mi ejemplo y no dejes\n"
	.string "de luchar!$"

gFameCheckerPersonName_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de LANCE\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Me estoy planteando\n"
	.string "volver a mi lugar de origen.\p"
	.string "Quiero entrenar de nuevo a mis\n"
	.string "POKéMON y fortalecerlos un poco.\p"
	.string "Espero verte por allí algún día\n"
	.string "de estos.$"

gFameCheckerPersonName_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BILL\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Eh, oye! ¡CELIO no hace más\n"
	.string "que hablar de ti, te pone por\l"
	.string "las nubes!\p"
	.string "¡Da gusto oírle!\p"
	.string "¡Oye, si atrapas POKéMON raros,\n"
	.string "ven a verme! ¡Hasta lueguito!$"

gFameCheckerPersonName_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SR. FUJI$"

gFameCheckerPersonQuote_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario del SR. FUJI\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Espero que no pienses sólo\n"
	.string "en el bienestar de tus POKéMON...\p"
	.string "Confío en que te preocupes por\n"
	.string "todos los POKéMON que hay...$"

gFameCheckerPersonName_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de GIOVANNI\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En realidad, no quiero decirte\n"
	.string "nada.\p"
	.string "Yo voy a concentrarme en mejorar\n"
	.string "y punto.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0::
	.string "PUEBLO PALETA$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "CIUDAD VERDE$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "CIUDAD CARMÍN$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "AQUARINTO$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "CIUDAD VERDE$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "MANSIÓN AZULONA$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "ISLA QUARTA$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "CIUDAD PLATEADA$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "GIM. PLATEADA$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "CIUDAD PLATEADA$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "RUTA 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MT. MOON$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "MUSEO PLATEADA$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CIUDAD CELESTE$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "GIMNASIO CELESTE$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "GIMNASIO CELESTE$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "ISLAS ESPUMA$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CABO CELESTE$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CIUDAD CELESTE$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "CIUDAD CARMÍN$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "GIMNASIO CARMÍN$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "GIMNASIO CARMÍN$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "GIMNASIO CARMÍN$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "GIMNASIO CARMÍN$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "CIUDAD CARMÍN$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CIUDAD AZULONA$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "GIMNASIO AZULONA$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "GIMNASIO AZULONA$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "GIMNASIO AZULONA$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "GIMNASIO AZULONA$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "MANSIÓN AZULONA$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "CIUDAD FUCSIA$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "GIMNASIO FUCSIA$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "GIMNASIO FUCSIA$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "CIUDAD FUCSIA$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "CIUDAD FUCSIA$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "ZONA SAFARI$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "CIUDAD AZAFRÁN$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "ISLA TERA$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "GIMNASIO AZAFRÁN$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "GIMNASIO AZAFRÁN$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "CIUDAD AZAFRÁN$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "GIMNASIO AZAFRÁN$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "ISLA CANELA$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "GIMNASIO CANELA$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "GIMNASIO CANELA$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "ISLA CANELA$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "GIMNASIO CANELA$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "LUGAR DE RECREO$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "ISLA QUARTA$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "ISLA INTA$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "ISLA QUARTA$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "ISLA QUARTA$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "CIUDAD AZAFRÁN$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "BALNEARIO ASCUAS$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "ISLA SECUNDA$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "CAÑÓN SÉTANO$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "MESETA AÑIL$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "MESETA AÑIL$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "ISLA SÉTIMA$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "ISLA EXTA$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "LIGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "CIUDAD AZAFRÁN$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CC AZULONA$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "MESETA AÑIL$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "MESETA AÑIL$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CIUDAD CELESTE$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CIUDAD CELESTE$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "CIUDAD FUCSIA$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "ISLA PRIMA$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "ISLA PRIMA$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "ISLA PRIMA$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "PUEBLO LAVANDA$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "TORRE POKéMON$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "PUEBLO LAVANDA$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "PUEBLO LAVANDA$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "GIMNASIO CANELA$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "ISLA CANELA$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "GUAR. ROCKET/CG$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH S.A.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH S.A.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "GIMNASIO VERDE$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "GIMNASIO VERDE$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ALMACÉN ROCKET$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. OAK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "AYUDANTE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "AYUDANTE$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "AYUDANTE$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "MUJER$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "HOMBRE$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "SEÑORA MAYOR$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "CHICO JOVEN$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "CHICO$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "HOMBRE$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "CHICO JOVEN$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "SEÑORA$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TITO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TITO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DIMAS$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "PURI$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "ÁNGEL$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "SACHIKO$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "HOMBRE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "CHICO JOVEN$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TOR$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "CARTEL$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DANTE$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "MUJER$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "PRIMA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "PRIMA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "SEÑOR MAYOR$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "NIÑA PEQUEÑA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "SEÑORA MAYOR$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "MACHACABAYAS$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "MUJER$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "MACHACABAYAS$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "MACHACABAYAS$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "MACHACABAYAS$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "SEÑORA MAYOR$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "MUJER$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "NIÑA PEQUEÑA$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "CHICO JOVEN$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "NIÑO PEQUEÑO$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "SEÑOR MAYOR$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "NIÑA PEQUEÑA$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "REVISTA$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "HOMBRE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "DIARIO POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "CIENTÍFICO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "CIENTÍFICO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "HOMBRE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIL$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre BROCK, LÍDER\n"
	.string "del GIMNASIO de PLATEADA.\p"
	.string "Según fuentes cercanas, BROCK\n"
	.string "casi nunca se ríe, ¡pero una vez\l"
	.string "que empieza, no para!$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre MISTY, LÍDER\n"
	.string "del GIMNASIO de CELESTE.\p"
	.string "Según fuentes cercanas, MISTY\n"
	.string "adora a PRIMA, del ALTO MANDO.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre LT. SURGE, LÍDER\n"
	.string "del GIMNASIO de CARMÍN.\p"
	.string "Según fuentes cercanas, LT. SURGE\n"
	.string "era piloto cuando vivía en Estados\l"
	.string "Unidos.\p"
	.string "Y se valía de la electricidad\n"
	.string "generada por sus POKéMON\l"
	.string "para poner en marcha su avión.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre ERIKA, LÍDER\n"
	.string "del GIMNASIO de AZULONA.\p"
	.string "Según fuentes cercanas, es fácil\n"
	.string "ver a ERIKA echándose una siesta\l"
	.string "en el GIMNASIO de AZULONA.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre KOGA, LÍDER\n"
	.string "del GIMNASIO de FUCSIA.\p"
	.string "Según fuentes cercanas, KOGA\n"
	.string "tiene grandes conocimientos\l"
	.string "de medicina.\p"
	.string "Incluso elabora las medicinas\n"
	.string "que sus POKéMON necesitan.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre SABRINA, LÍDER\n"
	.string "del GIMNASIO de AZAFRÁN.\p"
	.string "Según fuentes cercanas, SABRINA\n"
	.string "se comunica en combate con sus\l"
	.string "POKéMON, sin necesidad de hablar.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre BLAINE, LÍDER\n"
	.string "del GIMNASIO de CANELA.\p"
	.string "Según fuentes cercanas, BLAINE\n"
	.string "sólo se quita las gafas de sol\l"
	.string "cuando contesta a preguntas.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre PRIMA,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, PRIMA\n"
	.string "guarda un gran secreto.\p"
	.string "Lo que sí se conoce de ella es\n"
	.string "su estilo de lucha elegante, único\l"
	.string "y calculador.$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre BRUNO,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, BRUNO\n"
	.string "se unió al ALTO MANDO para luchar\l"
	.string "contra los mejores ENTRENADORES.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre AGATHA,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, AGATHA\n"
	.string "y el PROF. OAK estuvieron\p"
	.string "enfrentados durante su formación\n"
	.string "como ENTRENADORES.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre LANCE,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, quien fundó\n"
	.string "el clan de los maestros del tipo\l"
	.string "DRAGÓN fue el abuelo de LANCE.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre el PROF.\n"
	.string "OAK, el investigador de POKéMON.\p"
	.string "Según dicen, el PROF. OAK vive\n"
	.string "con su nieta DALIA y {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "Un DIARIO POKéMON de hace\n"
	.string "unos años...\p"
	.string "¡Especial sobre el CONCURSO\n"
	.string "del DIARIO POKéMON!\p"
	.string "¡La campeona de la edición de\n"
	.string "primavera del CONCURSO POKéMON\l"
	.string "es DALIA OAK, de PUEBLO PALETA!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre el SR. FUJI,\n"
	.string "de la CASA POKéMON.\p"
	.string "Nota del editor: el tímido\n"
	.string "SR. FUJI no ha querido contestar\l"
	.string "a nuestras preguntas.\p"
	.string "Con todo, hay que decir que es una\n"
	.string "persona muy querida en PUEBLO\l"
	.string "LAVANDA.$"
