Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "¡Voy a darme una vuelta con mi\n"
    .string "novia!$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "¡Vamos a pedalear juntos!$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Has usado los prismáticos...\p"
    .string "¡Es el CENTRO COMERCIAL\n"
    .string "de CIUDAD AZULONA!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Has usado los prismáticos...\p"
    .string "¡Hay un largo camino sobre\n"
    .string "el agua!$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "El PROFESOR me pidió premiar a\n"
    .string "Entrenadores que progresen.\p"
    .string "Me encargó darte MON. AMULETO\n"
    .string "si ya tienes la MEDALLA ARCOIRIS.\p"
    .string "¿Ya tienes la MEDALLA ARCOIRIS?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "¡Perfecto! Esa MEDALLA demuestra\n"
    .string "cuánto has avanzado.\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route16_NorthEntrance_2F_Text_NeedRainbowBadge::
    .string "Vuelve cuando consigas la\n"
    .string "MEDALLA ARCOIRIS.\p"
    .string "Guardaré MON. AMULETO para ti.$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "¡{PLAYER} obtuvo MON. AMULETO\n"
    .string "de manos del AYUDANTE!$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "Una MONEDA AMULETO es un objeto\n"
    .string "que puede llevar un POKéMON.\p"
    .string "Si gana el POKéMON que la tenga,\n"
    .string "conseguirás más dinero.$"
