PokemonMansion_B1F_Text_LewisIntro::
    .string "¡Oh, oh!\n"
    .string "¿Dónde estoy ahora?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "¡Vaya!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "Puedes recoger cosas del suelo.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "Este lugar es ideal para un\n"
    .string "laboratorio.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "¿Era esto lo que querías?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "¡Me encanta este sitio! ¡Es muy\n"
    .string "apropiado para mis estudios!$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Diario: 1 de septiembre.\n"
    .string "MEWTWO es demasiado poderoso.\p"
    .string "No hemos sabido contener sus malos\n"
    .string "instintos.$"


PokemonMansion_B1F_Text_FullMewFinalAppearance::
    .string "¡Miiiu!\p"
    .string "MEW aparece frente al diario.\n"
    .string "Ya no parece querer esconderse.$"
