FuchsiaCity_Gym_Text_KogaIntro::
    .string "¡Uajajaja! Soy KOGA,\nmaestro de las artes ninja.\p"
    .string "No solo gana el más fuerte: \nel veneno y la paciencia\lpueden decidir un combate.\p"
    .string "¡Intenta leer mis movimientos!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "¡Impresionante!\p"
    .string "Has descubierto mis engaños.\nLa MEDALLA ALMA es tuya.$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "El veneno castiga a quien\nse confía demasiado.\p"
    .string "Observa a tu rival,\ny no desperdicies un turno.$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "¡Ahora que tienes la MEDALLA ALMA,\n"
    .string "la DEFENSA de tus POKéMON\l"
    .string "aumentará!\p"
    .string "¡Y podrás hacer SURF siempre\n"
    .string "que quieras!\p"
    .string "¡Ah!\n"
    .string "¡Llévate esto también!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "¡{PLAYER} obtuvo la MT06\n"
    .string "de manos de KOGA!$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "La MT06 enseña TÓXICO.\p"
    .string "El veneno se agrava\ncon cada turno que pasa.\p"
    .string "¡Es una técnica ninja\ntransmitida por generaciones!$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Hasta un ninja necesita espacio.\n¡Vacía tu mochila y vuelve!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "La fuerza no es la clave con los\n"
    .string "POKéMON, ¿sabes?\p"
    .string "¡La estrategia es lo importante!\p"
    .string "¡Te enseñaré cómo la estrategia\n"
    .string "puede vencer a la fuerza!$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "¡Extraordinario!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "¿Mezclarás fuerza e inteligencia?\n"
    .string "¡Buena táctica!\p"
    .string "¡Es asombroso lo que sabes\n"
    .string "con lo joven que eres!$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "¡Quería ser un ninja y por eso\n"
    .string "vine a este GIMNASIO!$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "¡Vaya, he perdido!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "¡Seguiré entrenándome con KOGA,\n"
    .string "mi maestro ninja!$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "¡A ver si superas mis técnicas\n"
    .string "especiales!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "¡Me has dejado alucinado!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "¡Me gustan los ataques de sueño\n"
    .string "y veneno porque perduran tras\l"
    .string "el combate!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "¡Alto ahí!\p"
    .string "¿Te han agobiado nuestros muros\n"
    .string "invisibles?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "¡Buaaa!\n"
    .string "¡Qué bien luchas!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "¡Impresionante!\p"
    .string "Oye, una cosa: mira bien entre\n"
    .string "los huecos de los muros invisibles.$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "¡También estudio técnicas ninja\n"
    .string "con el maestro KOGA!\p"
    .string "¡Los ninja llevan mucho tiempo\n"
    .string "usando animales!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "¡Auuuu!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "¡Me queda mucho por aprender!$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "¡El maestro KOGA desciende\n"
    .string "de una gran familia de ninjas!\p"
    .string "¿Y tú de qué familia desciendes?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Eres más fuerte de lo que\n"
    .string "pensaba...$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "¡Donde hay luz hay sombras!\p"
    .string "¡Luz o sombra!\n"
    .string "¿Cuál eliges?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "¡Hola, aspirante al título!\p"
    .string "¡El GIMNASIO FUCSIA está lleno de\n"
    .string "muros invisibles!\p"
    .string "¡Podría parecer que KOGA está\n"
    .string "cerca, pero hay muros invisibles\l"
    .string "que lo protegen!\p"
    .string "¡Busca huecos entre los muros\n"
    .string "para llegar hasta él!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "¡Es increíble lo terribles que\n"
    .string "pueden ser los ninjas!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
