OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: Eccoci qui!\n"
    .string "Siamo arrivati a PRIMISOLA.\p"
    .string "È una delle tante isole che\n"
    .string "formano il SETTIPELAGO.\p"
    .string "È stato il mio amico CELIO a\n"
    .string "mandare la barca che ci ha\l"
    .string "portato qui.\p"
    .string "CELIO è il responsabile della rete\n"
    .string "di PC dell'isola.\p"
    .string "Sì, ma cosa te ne parlo a fare?\n"
    .string "Faccio prima a presentartelo!$"

Text_WhereDoYouWantToSail::
    .string "Allora, dove vuoi andare?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "Quest'isola è completamente\n"
    .string "isolata dal resto del mondo.\p"
    .string "Meno male che c'è CELIO! È un\n"
    .string "tipo in gamba, sai?\p"
    .string "Ora mia nipote è tutta esaltata per\n"
    .string "l'arrivo di un amico di CELIO.\p"
    .string "Pare che sia un famoso\n"
    .string "POKéFANATICO.\p"
    .string "Se è un amico di CELIO,\n"
    .string "dev'essere una persona\l"
    .string "a modo!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Mia nipote mi ha raccontato di una\n"
    .string "grande novità: era tutta esaltata!\p"
    .string "Se ho capito bene, ora c'è un\n"
    .string "collegamento via PC con KANTO.\p"
    .string "Se è una trovata di CELIO, non\n"
    .string "può che essere geniale.$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "Mia nipote mi ha raccontato di una\n"
    .string "grande novità: era tutta esaltata!\p"
    .string "Se ho capito bene, ora c'è un\n"
    .string "collegamento via PC con HOENN.\p"
    .string "Se è una trovata di CELIO, non\n"
    .string "può che essere geniale.\p"
    .string "Sarebbe l'uomo giusto per mia\n"
    .string "nipote.$"

OneIsland_Text_IslandSign::
    .string "PRIMISOLA\n"
    .string "L'isola del collegamento!$"

OneIsland_Text_PokemonNetCenterSign::
    .string "Il mondo si espande!\n"
    .string "CENTRO POKéMON TELEMATICO$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Stai facendo un giro? Il clima è\n"
    .string "fantastico da queste parti, vero?$"

OneIsland_Text_FullBeastFirstContact::
    .string "An unnatural silence falls over the island...\p"
    .string "Three POKéMON appear together.\n"
    .string "SUICUNE steps forward while RAIKOU and\n"
    .string "ENTEI watch from behind.$"

OneIsland_Text_FullBeastTrioFlees::
    .string "All three fix their gaze on {PLAYER}.\p"
    .string "Suddenly they split up and vanish at\n"
    .string "incredible speed.\p"
    .string "SUICUNE seems to have stayed nearby.\n"
    .string "Its route can now be tracked in the POKéDEX.$"

