OneIsland_Text_BillLetsGoSeeCelio::
	.string "LEO: On y est!\n"
	.string "Voilà l'ILE 1.\p"
	.string "Il y a plusieurs îles dans le coin,\n"
	.string "nous sommes sur l'une d'elles.\p"
	.string "Mon ami CILEO a mis ce bateau \n"
	.string "à ma disposition pour venir ici.\p"
	.string "Il a la responsabilité du réseau\n"
	.string "informatique de l'île.\p"
	.string "Mais tu auras une meilleure idée\n"
	.string "en le rencontrant, allons-y!$"

Text_WhereDoYouWantToSail::
	.string "Ohé, moussaillon!\n"
	.string "Où veux-tu aller?$"

OneIsland_Text_LuckyToHaveCelioHere::
	.string "Sur cette île, nous sommes vraiment\n"
	.string "au milieu de nulle part.\p"
	.string "Nous avons beaucoup de chance\n"
	.string "d'avoir quelqu'un comme CILEO.\p"
	.string "Ma petite-fille se met dans tous\n"
	.string "ses états pour un ami de CILEO.\p"
	.string "Quelque chose à voir avec un\n"
	.string "POKéMANIAC, ou un truc du genre.\p"
	.string "Je ne suis pas sûr de comprendre,\n"
	.string "mais CILEO est vraiment génial.$"

OneIsland_Text_HavePCLinkageWithKanto::
	.string "Ma petite-fille est toute excitée\n"
	.string "par une nouvelle invention.\p"
	.string "Elle dit que nous sommes connectés\n"
	.string "aux habitants de KANTO.\p"
	.string "Je ne suis pas sûr de comprendre,\n"
	.string "mais CILEO est vraiment génial.$"

OneIsland_Text_HavePCLinkageWithHoenn::
	.string "Ma petite-fille est toute excitée\n"
	.string "par une nouvelle invention.\p"
	.string "Elle dit que nous sommes enfin\n"
	.string "connectés aux habitants de HOENN.\p"
	.string "Je ne suis pas sûr de comprendre,\n"
	.string "mais CILEO est vraiment génial.\p"
	.string "Ce serait le mari idéal pour ma\n"
	.string "petite-fille.$"

OneIsland_Text_IslandSign::
	.string "ILE 1\n"
	.string "Les amis se réunissent ici$"

OneIsland_Text_PokemonNetCenterSign::
	.string "Pour relier le monde entier\n"
	.string "CENTRE RESEAU POKéMON$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
	.string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
	.string "Bonjour, tu fais du tourisme?\n"
	.string "Tu aimes le coin?$"

OneIsland_Text_FullBeastFirstContact::
    .string "An unnatural silence falls over the island...\p"
    .string "Three POKéMON appear together.\n"
    .string "SUICUNE steps forward while RAIKOU and\n"
    .string "ENTEI watch from behind.$"

OneIsland_Text_FullBeastTrioFlees::
    .string "All three fix their gaze on {PLAYER}.\p"
    .string "Suddenly they split up and vanish at\n"
    .string "incredible speed.\p"
    .string "SUICUNE seems to have stayed nearby.\n"
    .string "Its route can now be tracked in the POKéDEX.$"

