PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "Este lugar es...\n"
    .string "¡Gigantesco!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "¡Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "Me pregunto adónde habrá ido\n"
    .string "mi compañero.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "Mi maestro vivió aquí hace tiempo.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "¡Uau!\n"
    .string "¡Impresionante!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "¿No sabes por dónde ir?\n"
    .string "¡Tírate por ahí!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Diario: 6 de febrero.\n"
    .string "MEW dio a luz.\p"
    .string "Llamamos al pequeño: MEWTWO.$"


PokemonMansion_3F_Text_FullMewSighting3::
    .string "La misma presencia vuelve a sentirse.\p"
    .string "Esta vez desciende hacia las zonas\n"
    .string "más profundas de la MANSIÓN.$"
