Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
	.string "Hi! Remember me?\n"
	.string "I'm one of PROF. OAK's AIDES.\p"
	.string "PROF. OAK asked me to reward\n"
	.string "Trainers who keep progressing.\p"
	.string "He entrusted me with HM05 for you.\p"
	.string "If you've earned the CASCADE BADGE,\n"
	.string "this reward is yours.\p"
	.string "Have you earned the CASCADE BADGE?$"

Route2_EastBuilding_Text_GreatHereYouGo::
	.string "Great! That BADGE shows how far\n"
	.string "you've come as a Trainer.\p"
	.string "Congratulations!\n"
	.string "Here you go!$"

Route2_EastBuilding_Text_NeedCascadeBadge::
	.string "Come back after you've earned the\n"
	.string "CASCADE BADGE.\p"
	.string "I'll keep HM05 safe for you.$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
	.string "{PLAYER} received HM05\n"
	.string "from the AIDE.$"

Route2_EastBuilding_Text_ExplainHM05::
	.string "HM05 contains the hidden move\n"
	.string "FLASH.\p"
	.string "FLASH lights up even the darkest\n"
	.string "of caves and dungeons.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
	.string "Once a POKéMON learns FLASH, you\n"
	.string "can get through ROCK TUNNEL.$"
