Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "El PROFESOR me pidió premiar a\n"
    .string "Entrenadores que progresen.\p"
    .string "Me encargó darte la MO05 si ya\n"
    .string "conseguiste la MEDALLA CASCADA.\p"
    .string "¿Ya tienes la MEDALLA CASCADA?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "¡Perfecto! Esa MEDALLA demuestra\n"
    .string "cuánto has avanzado.\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route2_EastBuilding_Text_NeedCascadeBadge::
    .string "Vuelve cuando consigas la\n"
    .string "MEDALLA CASCADA.\p"
    .string "Guardaré la MO05 para ti.$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "¡{PLAYER} obtuvo la MO05\n"
    .string "de manos del AYUDANTE!$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "El DESTELLO de la MO ilumina hasta\n"
    .string "las más oscuras mazmorras.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Si un POKéMON aprende DESTELLO,\n"
    .string "podrás cruzar el TÚNEL ROCA.$"
