SaffronCity_Gym_Text_SabrinaIntro::
    .string "Sabía que vendrías.\p"
    .string "Soy SABRINA. Desde niña\npuedo mover objetos\lcon la mente.\p"
    .string "No disfruto del combate,\npero respeto tu determinación.\p"
    .string "Muéstrame qué camino eliges.{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "No había previsto\nesta posibilidad...\p"
    .string "Acepto mi derrota.\nTe has ganado la MEDALLA PANTANO.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "La mente cambia\ncuando aprendemos a escuchar.\p"
    .string "Tu vínculo con tus POKéMON\nte permitirá ir aún más lejos.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "¡Con la MEDALLA PANTANO, todo\n"
    .string "POKéMON con nivel inferior a 70 te\l"
    .string "obedecerá!\p"
    .string "¡Los POKéMON más fuertes\n"
    .string "suelen desobedecer las órdenes\l"
    .string "en combate!\p"
    .string "¡No entrenes demasiado a tus\n"
    .string "POKéMON para evitar este\l"
    .string "problema!\p"
    .string "¡Espera, llévate esta MT!$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "¡{PLAYER} obtuvo la MT04\n"
    .string "de manos de SABRINA!$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "La MT04 enseña PAZ MENTAL.\p"
    .string "Concentrarse refuerza el\nATAQUE ESP. y la DEFENSA ESP.\p"
    .string "La calma también es poder.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "¡Tu mochila está llena de otros\n"
    .string "objetos!$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "¡SABRINA es más joven que yo,\n"
    .string "pero la respeto!$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "¡Vaya fallo!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "¡En una pelea de iguales, ganará\n"
    .string "quien tenga más voluntad!\p"
    .string "¡Si quieres ganar a SABRINA,\n"
    .string "piensa sólo en ganar!$"

SaffronCity_Gym_Text_JohanIntro::
    .string "¿Te asusta nuestro poder oculto?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "¡Jamás lo hubiera pensado!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "¡Los POKéMON psíquicos temen sólo\n"
    .string "a los bichos y a los fantasmas!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "Los POKéMON acaban pareciéndose\n"
    .string "a sus ENTRENADORES.\p"
    .string "¡Pues tus POKéMON parecen fuertes!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "¡Lo sabía!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "¡Debo enseñarles mejores técnicas\n"
    .string "a mis POKéMON!\p"
    .string "¡Sobre todo del tipo PSÍQUICO!$"

SaffronCity_Gym_Text_TyronIntro::
    .string "Sabes que tu fuerza no bastará\n"
    .string "para ganar en el mundo de los\l"
    .string "POKéMON, ¿no?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "¡No me lo puedo creer!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "¡SABRINA ganó al MAESTRO de\n"
    .string "KARATE de la puerta de al lado!$"

SaffronCity_Gym_Text_TashaIntro::
    .string "¡Tú y yo!\n"
    .string "Nuestros POKéMON deben luchar.$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "¡He perdido al final!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Sabía que esto iba a pasar.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "¡SABRINA es joven, pero es nuestra\n"
    .string "LÍDER!\p"
    .string "¡No llegarás a ella fácilmente!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "¡No he podido concentrarme!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "En AZAFRÁN había dos\n"
    .string "GIMNASIOS POKéMON.\p"
    .string "¡El DOJO-KARATE de aquí al lado\n"
    .string "perdió su condición de GIMNASIO\l"
    .string "cuando los machacamos!$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "¡El GIMNASIO POKéMON de AZAFRÁN\n"
    .string "es famoso por sus médiums!\p"
    .string "¡Quieres ver a SABRINA!\n"
    .string "¡Lo sé!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "¡Arrrgg!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "¡Tienes razón! ¡Usé la telepatía\n"
    .string "para leer tu mente!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "¡Hola, aspirante al título!\p"
    .string "¡Los POKéMON de SABRINA usan el\n"
    .string "poder de la mente, no la fuerza!\p"
    .string "¡Los POKéMON del tipo LUCHA\n"
    .string "son débiles contra los de tipo\l"
    .string "PSÍQUICO!\p"
    .string "¡Se debilitan casi antes de poder\n"
    .string "prepararse!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "¿Poder mental?\p"
    .string "¡Si yo lo tuviera me haría rico en\n"
    .string "las tragaperras!$"

SaffronCity_Gym_Text_GymStatue::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZAFRÁN: SABRINA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZAFRÁN: SABRINA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
