CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
	.string "Ich?\n"
	.string "Ich bin der Programmierer!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
	.string "Ich bin der Grafiker!\n"
	.string "Ich habe dies alles gezeichnet!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
	.string "Die Geschichte stammt von mir!\n"
	.string "Ist ERIKA nicht süß?\p"
	.string "Aber MISTY mag ich auch gerne!\n"
	.string "Und nicht zu vergessen, SABRINA!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
	.string "Gefällt dir das Spiel?\p"
	.string "Ich habe das Spiel gestaltet!\p"
	.string "Auch wenn es sehr mühsam ist, den\n"
	.string "POKéDEX zu erstellen: Gib nicht\l"
	.string "auf!\p"
	.string "Zeige ihn mir, wenn er komplett ist!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
	.string "Wow! Fantastisch!\n"
	.string "Dein POKéDEX ist vollständig!\l"
	.string "Herzlichen Glückwunsch!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
	.string "Der Programmcode! Davon sollte man\n"
	.string "besser die Finger lassen!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
	.string "Dort spielt jemand, anstatt zu\n"
	.string "arbeiten!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
	.string "Das Drehbuch! Ich schaue mir das\n"
	.string "Ende besser nicht an!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
	.string "GAME FREAK Entwicklungs-Abteilung$"


CeladonCity_Condominiums_3F_Text_KantoExtraPrize::
    .string "Du hast den KANTO-POKéDEX\nvervollständigt!\p"
    .string "Zusätzlich zum Diplom\nerhältst du einen Preis!$"

CeladonCity_Condominiums_3F_Text_KantoReceivedMasterBall::
    .string "Du erhältst einen MEISTERBALL!$"

CeladonCity_Condominiums_3F_Text_KantoMasterBallNoRoom::
    .string "Deine TASCHE ist voll.\p"
    .string "Mach Platz und komm zurück.\nDer Preis wartet auf dich!$"
