CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "¿Yo?\n"
    .string "¡Soy el programador!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "¡Soy el diseñador gráfico!\n"
    .string "¡Yo te dibujé!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "¡Yo escribí la historia!\n"
    .string "¿A que es guapa ERIKA?\p"
    .string "¡También me gusta mucho MISTY!\n"
    .string "¡Y también me gusta SABRINA!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "¿Sabes?\p"
    .string "¡Soy el diseñador del juego!\p"
    .string "¡Completar tu POKéDEX es difícil,\n"
    .string "pero no te rindas!\p"
    .string "¡Cuando termines ven a decírmelo!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "¡Uauu! ¡Genial!\n"
    .string "¡Has completado tu POKéDEX!\l"
    .string "¡Enhorabuena!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "¡Es el programa del juego!\n"
    .string "¡No lo toques, no vaya a ser que\l"
    .string "se estropee!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "¡Alguien está jugando en lugar\n"
    .string "de trabajar!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "¡Es el guión del juego!\n"
    .string "¡No leas el final!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "Sala de desarrollo de GAME FREAK$"

CeladonCity_Condominiums_3F_Text_KantoExtraPrize::
    .string "¡Has completado la POKéDEX\nde KANTO!\p"
    .string "Además del diploma, tu\nesfuerzo merece un premio.\p"
    .string "¡Te entregaré una MASTER BALL!$"

CeladonCity_Condominiums_3F_Text_KantoReceivedMasterBall::
    .string "¡Has recibido una MASTER BALL!$"

CeladonCity_Condominiums_3F_Text_KantoMasterBallNoRoom::
    .string "No tienes espacio en la mochila.\p"
    .string "Guarda algo y vuelve:\nel premio te esperará.$"
