CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Io?\n"
    .string "Sono il programmatore!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "Sono il grafico che ti ha\n"
    .string "disegnato!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "Ho scritto la storia!\n"
    .string "Non è forte ERIKA?\p"
    .string "Mi piace molto anche MISTY!\n"
    .string "Per non parlare di SABRINA!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Va bene?\p"
    .string "Ho progettato questo gioco!\p"
    .string "Completare il tuo POKéDEX è\n"
    .string "difficile, ma non arrenderti!\p"
    .string "Quando hai finito vieni a dirmelo!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Wow! Eccellente!\n"
    .string "Hai completato il tuo POKéDEX!\l"
    .string "Congratulazioni!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "È il programma del gioco! Non lo\n"
    .string "toccare, potrebbe esplodere!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Qualcuno sta giocando invece di\n"
    .string "lavorare!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "È il copione!\n"
    .string "Ma non leggere il finale!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "GAME FREAK - Sala sviluppo$"


CeladonCity_Condominiums_3F_Text_KantoExtraPrize::
    .string "Hai completato il POKéDEX\ndi KANTO!\p"
    .string "Oltre al diploma, meriti\nun premio speciale!$"

CeladonCity_Condominiums_3F_Text_KantoReceivedMasterBall::
    .string "Hai ricevuto una MASTER BALL!$"

CeladonCity_Condominiums_3F_Text_KantoMasterBallNoRoom::
    .string "La BORSA è piena.\p"
    .string "Fai spazio e torna qui.\nIl premio ti aspetterà!$"
