CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
	.string "Moi?\n"
	.string "J'suis un programmeur!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
	.string "Je fais tous les graphismes!\n"
	.string "J'ai même créé ton personnage!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
	.string "J'ai écrit l'histoire!\n"
	.string "ERIKA est belle!\p"
	.string "ONDINE aussi, non?\n"
	.string "Et puis MORGANE! Elle est mimi!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
	.string "Je suis le concepteur du jeu!\p"
	.string "Remplir ton POKéDEX est difficile,\n"
	.string "hein?\p"
	.string "Complète-le et reviens me voir!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
	.string "Woah! Génial!\n"
	.string "Tu as complété ton POKéDEX!\l"
	.string "Félicitations!\l"
	.string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
	.string "Le programme du jeu! Si tu y\n"
	.string "touches, tout va planter!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
	.string "Quelqu'un joue au lieu de bosser!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
	.string "Le script du jeu!\n"
	.string "Surtout ne pas lire la fin!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
	.string "GAME FREAK Développement$"


CeladonCity_Condominiums_3F_Text_KantoExtraPrize::
    .string "Tu as complété le POKéDEX\nde KANTO!\p"
    .string "En plus du diplôme, voici\nune récompense spéciale!$"

CeladonCity_Condominiums_3F_Text_KantoReceivedMasterBall::
    .string "Tu reçois une MASTER BALL!$"

CeladonCity_Condominiums_3F_Text_KantoMasterBallNoRoom::
    .string "Ton SAC est plein.\p"
    .string "Fais de la place et reviens.\nLe prix t'attendra!$"
