RocketHideout_B4F_Text_GiovanniIntro::
    .string "Así que has llegado\nhasta mi guarida.\p"
    .string "Soy GIOVANNI, líder del\nTEAM ROCKET.\p"
    .string "Los POKéMON son la fuerza\nque sostiene mis planes.\p"
    .string "No permitiré que un intruso\narruine lo que he construido.$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "¿Cómo...?\n¡No esperaba esta derrota!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "Has entrenado con habilidad.\nEso no puedo negarlo.\p"
    .string "Pero aún no comprendes\nel alcance de mis planes.\p"
    .string "Por esta vez, me retiraré.\nVolveremos a encontrarnos.$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "¡Te conozco! ¡Tú arruinaste\n"
    .string "nuestros planes en MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "¡Me han vuelto a machacar!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "¿Tienes algo en contra del TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "¿Acaso no ves la belleza de\n"
    .string "nuestros actos malvados?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "¡Ayayay!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "¡JEFE!\n"
    .string "¡Siento haberle fallado!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "¿No funciona el ascensor? ¿Quién\n"
    .string "tiene la LLAVE del ASCENSOR?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "¡No!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "¡Oh, no! ¡He perdido la LLAVE\n"
    .string "del ASCENSOR!$"
