FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "PRIMA: ¡Ni te acerques a los\n"
    .string "POKéMON que hay en la cueva!\p"
    .string "Si no, te las tendrás que ver\n"
    .string "conmigo.$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Venga ya, señora, no incordie.\p"
    .string "¡Chicos, sigamos a lo nuestro!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "PRIMA: ¡¿{PLAYER}?!\n"
    .string "¿Qué haces aquí?\p"
    .string "Bueno, ya charlaremos después.\n"
    .string "Ayúdame con estos elementos.\p"
    .string "Necesito que me eches una mano\n"
    .string "para frenar a esta gentuza.\p"
    .string "Han estado atrapando POKéMON\n"
    .string "aquí, y vendiéndolos por ahí.\p"
    .string "¿Vas a ayudarme?\n"
    .string "¡Pues adelante!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "¿Perdón?\p"
    .string "¿Quién dice aquí lo que podemos\n"
    .string "o no podemos hacer con los\l"
    .string "POKéMON que atrapamos?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "¡No me esperaba yo esto!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "PRIMA: Ja.\n"
    .string "Qué cosa más endeble...\p"
    .string "A ver, tú.\n"
    .string "Dime.\p"
    .string "¿Dónde tenéis a los POKéMON\n"
    .string "que habéis capturado?\p"
    .string "Dímelo ahora mismo si no quieres\n"
    .string "que te dé una zurra.$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "¡Ni en broma!\n"
    .string "¡No pienso decírtelo!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "PRIMA: Como no me lo digas,\n"
    .string "¡acabarás congelado!\p"
    .string "Mi LAPRAS está que trina por lo\n"
    .string "que les habéis hecho a sus amigos.\p"
    .string "¡Venga, LAPRAS!\n¡RAYO HIELO!...$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "¡Aaaaah!\n"
    .string "¡Para, para, que te lo digo!\p"
    .string "Los POKéMON están en el ALMACÉN\n"
    .string "ROCKET de ISLA INTA.\p"
    .string "¡Hala, ya lo he dicho!\n"
    .string "¡Vámonos ya de aquí!\p"
    .string "¡Pero que sepas que dudo mucho\n"
    .string "que puedas entrar en el ALMACÉN\l"
    .string "ROCKET!\p"
    .string "¡Ja, ja, ja!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, gracias.\n"
    .string "Ha sido horrible...\p"
    .string "Yo he nacido aquí y he pasado\n"
    .string "toda mi vida en estas islas.\p"
    .string "No sabía que esos golfos\n"
    .string "estuvieran por aquí sueltos...$"
