FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "PRIMA: No me puedo quitar una\n"
    .string "cosa de la cabeza...\p"
    .string "Si ocurriera algo a la isla en la\n"
    .string "que nací...\p"
    .string "No me enteraría si estuviera\n"
    .string "en la LIGA POKéMON.\p"
    .string "Entonces, sería responsable\n"
    .string "de lo ocurrido, ¿no?$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "PRIMA: ¿Que tú has solucionado\n"
    .string "todos los problemas?\p"
    .string "Qué maravilla...\p"
    .string "Entonces, no tengo que quedarme\n"
    .string "aquí todo el tiempo...\p"
    .string "¡Gracias!\p"
    .string "¡En ese caso, me volveré a la\n"
    .string "LIGA POKéMON!$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "No sé qué pasará dentro de un\n"
    .string "tiempo, así que...\p"
    .string "Haré lo que tenga que hacer\n"
    .string "aquí y ahora.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "¡Qué cantidad de MUÑECOS POKéMON\n"
    .string "de peluche!$"
