VermilionCity_Text_GrimerMultipliesInSludge::
	.string "Wir sind sehr umweltbewusst!\p"
	.string "Wir haben gehört, dass SLEIMA sich\n"
	.string "in giftigem Dreck wohl fühlt und\l"
	.string "entwickelt!$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
	.string "Hast du gesehen?\n"
	.string "Die M.S. ANNE ankert im Hafen!$"

VermilionCity_Text_SSAnneHasDepartedForYear::
	.string "Die M.S. ANNE ist ausgelaufen!\p"
	.string "Sie wird in einem Jahr wieder hier\n"
	.string "anlegen.$"

VermilionCity_Text_BuildingOnThisLand::
	.string "Ich möchte auf diesem Land bauen.\n"
	.string "Mein POKéMON ebnet den Boden!$"

VermilionCity_Text_Machop::
	.string "MACHOLLO: Macho! MACHOLLO!$"

VermilionCity_Text_MachopStompingLandFlat::
	.string "Ein MACHOLLO ebnet das Land!$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
	.string "Die M.S. ANNE ist ein luxuriöses\n"
	.string "Kreuzfahrtschiff.\p"
	.string "Wir besuchen ORANIA CITY einmal\n"
	.string "im Jahr.$"

VermilionCity_Text_CitySign::
	.string "ORANIA CITY\n"
	.string "Die Hafenstadt der einmaligen\l"
	.string "Sonnenuntergänge!$"

VermilionCity_Text_SnorlaxBlockingRoute12::
	.string "ACHTUNG!\p"
	.string "ROUTE 12 wird von einem\n"
	.string "schlafenden POKéMON blockiert.\p"
	.string "Umleitung: FELSTUNNEL nach\n"
	.string "LAVANDIA.\p"
	.string "POLIZEI VON ORANIA CITY$"

VermilionCity_Text_PokemonFanClubSign::
	.string "POKéMON-FANCLUB\n"
	.string "Alle POKéMON-Fans sind willkommen!$"

VermilionCity_Text_GymSign::
	.string "ORANIA CITY POKéMON-ARENA\n"
	.string "ARENALEITER: MAJOR BOB\l"
	.string "Der Blitzschnelle Arenaleiter!$"

VermilionCity_Text_VermilionHarbor::
	.string "HAFEN VON ORANIA CITY$"

VermilionCity_Text_WelcomeToTheSSAnne::
	.string "Willkommen an Bord!$"

VermilionCity_Text_DoYouHaveATicket::
	.string "Willkommen auf der M.S. ANNE!\p"
	.string "Verzeihung, hast du ein Ticket?$"

VermilionCity_Text_FlashedSSTicket::
	.string "{FONT_NORMAL}{PLAYER} zeigt das BOOTSTICKET!\p"
	.string "{FONT_MALE}Großartig!\n"
	.string "Willkommen auf der M.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
	.string "{FONT_NORMAL}{PLAYER} hat kein BOOTSTICKET!\p"
	.string "{FONT_MALE}Tut mir Leid!\p"
	.string "Du brauchst ein Ticket, um an Bord\n"
	.string "gehen zu können.$"

VermilionCity_Text_TheShipSetSail::
	.string "Das Schiff ist in See gestochen!$"

VermilionCity_Text_BoardSeagallopTriPass::
	.string "Ah, du hast den TRI-PASS.\p"
	.string "Möchtest du an Bord der\n"
	.string "SEESPRINT-Fähre?$"

VermilionCity_Text_Seagallop7Departing::
	.string "O.K.! Alles klar!\p"
	.string "SEESPRINT TEMPO 7 wird in\n"
	.string "Kürze ablegen.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
	.string "Ah, du hast den BUNT-PASS.\p"
	.string "Möchtest du an Bord der\n"
	.string "SEESPRINT-Fähre?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
	.string "Oh! Das ist das GEHEIMTICKET!\n"
	.string "Das ist selten.\p"
	.string "Wir bringen dich gerne zum\n"
	.string "NABELFELS.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
	.string "Oh! Das ist das AURORATICKET!\n"
	.string "Das ist selten.\p"
	.string "Wir bringen dich gerne zur\n"
	.string "ENTSTEHUNGSINSEL.$"

VermilionCity_Text_BoardSeagallopFerry::
	.string "Möchtest du an Bord der\n"
	.string "SEESPRINT-Fähre?$"

VermilionCity_Text_Seagallop10Departing::
	.string "O.K.! Alles klar! Du kannst an Bord\n"
	.string "der Spezialfähre.\p"
	.string "SEESPRINT TEMPO 10 wird \n"
	.string "sofort ablegen.$"

VermilionCity_Text_Seagallop12Departing::
	.string "O.K.! Alles klar! Du kannst an Bord\n"
	.string "der Spezialfähre.\p"
	.string "SEESPRINT TEMPO 12 wird \n"
	.string "sofort ablegen.$"

VermilionCity_Text_Route2AideHasPackageForYou::
	.string "Oh, hallo, {PLAYER}!\n"
	.string "Wie geht es dir?\p"
	.string "Ich bin es, einer von PROF. EICHs\n"
	.string "ASSISTENTEN.\p"
	.string "Hast du bereits einen anderen\n"
	.string "ASSISTENTEN getroffen?\p"
	.string "Er hatte ein Paket von PROF. EICH\n"
	.string "für dich, {PLAYER}.\p"
	.string "Er sagte, er sucht dich bei\n"
	.string "ROUTE 2, {PLAYER}.\p"
	.string "Wenn du bei ROUTE 2 bist, \n"
	.string "halte nach ihm Ausschau.$"

VermilionCity_Text_FullMaritimeBirdClue::
    .string "MATROSE: Drei seltene Vogel-PKMON\n"
    .string "wurden in KANTO gesichtet.\p"
    .string "Danach kam derselbe tiefe Ruf vom\n"
    .string "Meer. Frag im Hafen von EILAND EINS.$"
