PokemonLeague_LoreleisRoom_Text_Intro::
    .string "¡Ésta es la LIGA POKéMON!\p"
    .string "¡Yo soy PRIMA, del ALTO MANDO!\p"
    .string "¡Nadie me supera con los POKéMON\n"
    .string "que congelan!\p"
    .string "¡Los movimientos que hielan son\n"
    .string "muy potentes!\p"
    .string "¡Tus POKéMON estarán a mi merced\n"
    .string "cuando los congele!\p"
    .string "¡Ja! ¡Ja! ¡Ja!\n"
    .string "¿Comenzamos?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "¡Ésta es la LIGA POKéMON!\p"
    .string "¡Yo soy PRIMA, del ALTO MANDO!\n"
    .string "¡Aquí me tienes de nuevo!\p"
    .string "¡Ya sabes que nadie me supera\n"
    .string "con los POKéMON que congelan!\p"
    .string "¡Los movimientos que hielan son\n"
    .string "muy potentes!\p"
    .string "¡Tus POKéMON estarán a mi merced\n"
    .string "cuando los congele!\p"
    .string "¡Ja! ¡Ja! ¡Ja!\n"
    .string "¿Comenzamos?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "¡Esto no debería ser así!...$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "¡Eres mejor de lo que yo pensaba!\n"
    .string "¡Adelante!\p"
    .string "¡Pero la LIGA POKéMON te reserva\n"
    .string "otras sorpresas!$"
