CeladonCity_Gym_Text_ErikaIntro::
    .string "Oh... ¡Bienvenido a AZULONA!\p"
    .string "Soy ERIKA. Me gustan las flores\ny los POKéMON de tipo PLANTA.\p"
    .string "Un jardín exige paciencia,\npero también mucha firmeza.\p"
    .string "¿Probamos tu habilidad?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Oh... qué combate tan bello.\p"
    .string "Has superado a mis POKéMON.\nTe concedo la MEDALLA ARCOIRIS.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "La belleza de un POKéMON\nreside también en su esfuerzo.\p"
    .string "Has cuidado muy bien\nde tus compañeros.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "La MEDALLA ARCOIRIS hará que los\n"
    .string "POKéMON de nivel inferior a 50 te\l"
    .string "obedezcan.\p"
    .string "Y permitirá que los POKéMON usen\n"
    .string "FUERZA siempre que quieras.\p"
    .string "¡Ah, llévate esto también!$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "¡{PLAYER} recibió la MT19\n"
    .string "de manos de ERIKA!$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "La MT19 contiene GIGADRENADO.\p"
    .string "Absorbe energía del rival\ny cura a quien lo utiliza.\p"
    .string "¡Es como renovar un jardín!$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "Oh, tu mochila está llena.\nHaz espacio para esta MT.$"

CeladonCity_Gym_Text_KayIntro::
    .string "¿Sabes una cosa de este GIMNASIO?\p"
    .string "¡Es sólo para chicas!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "¡Eres demasiado fuerte!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "¡Eeeh!\n"
    .string "¡Espero que ERIKA acabe contigo!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Ah, hola.\n"
    .string "Estaba empezando a aburrirme.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "¡Oh! ¡Mi maquillaje!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "¡Los POKéMON del tipo PLANTA\n"
    .string "son difíciles para los acuáticos!\p"
    .string "¡Y tienen ventaja sobre los del\n"
    .string "tipo ROCA y los del tipo TIERRA!$"

CeladonCity_Gym_Text_TinaIntro::
    .string "Pero ¿tú no has estado ya por\n"
    .string "aquí?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "¡Estoy impresionada!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Ah, estabas buscando a ERIKA,\n"
    .string "no a mí.$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "¡Mira mis POKéMON del tipo\n"
    .string "PLANTA!\p"
    .string "¡Son tan fáciles de entrenar!...$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "¡No!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "¡En nuestro GIMNASIO sólo luchamos\n"
    .string "con POKéMON del tipo PLANTA!\p"
    .string "¡Y también los usamos para hacer\n"
    .string "adornos florales!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "¡Aquí no pueden entrar los POKéMON\n"
    .string "del tipo FUEGO o del tipo BICHO!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "¡Oh!\n"
    .string "¡Cómo eres!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "¡ERIKA, nuestra LÍDER, puede\n"
    .string "parecer muy tranquila, pero es muy\l"
    .string "hábil!$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Encantada de conocerte. A mí\n"
    .string "me encanta entrenar POKéMON.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "¡Oh!\n"
    .string "¡Espléndido!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Voy a tener una cita a ciegas.\n"
    .string "¡Y debo aprender buenos modales!$"

CeladonCity_Gym_Text_MaryIntro::
    .string "¡Éste es el GIMNASIO de AZULONA!\p"
    .string "¡Las encantadoras chicas que hay\n"
    .string "aquí son muy fuertes!$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "¡Me has ganado!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "¡No he traído a mis mejores\n"
    .string "POKéMON! ¡Ya verás la próxima\l"
    .string "vez!$"

CeladonCity_Gym_Text_GymStatue::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
