CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "¡Tengo sed!\n"
    .string "¡Me gustaría beber algo!\p"
#ifdef BUGFIX
    .string "{COLOR DARK_GRAY}¿Le das algo de beber?$"
#else
    .string "{FONT_NORMAL}¿Le das algo de beber?$"
#endif

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "¿Qué bebida quieres darle?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "¡Yay!\p"
    .string "¡AGUA!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"

Text_ReceivedItemFromLittleGirl::
    .string "¡{PLAYER} recibió la {STR_VAR_2}\n"
    .string "de manos de la chica!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "¡MT16 contiene PANTALLA LUZ!\p"
    .string "Reduce la fuerza de los AT. ESP.\n"
    .string "del rival.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "¡Genial!\p"
    .string "¡Un REFRESCO!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "¡MT20 contiene VELO SAGRADO!\p"
    .string "Evita los problemas de estado\n"
    .string "a tus POKéMON.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "¡Genial!\p"
    .string "¡LIMONADA!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "¡La MT33 contiene REFLEJO!\p"
    .string "Reduce la fuerza de los ataques\n"
    .string "físicos del rival.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "¡No tienes sitio para esto!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "¡No, gracias!\n"
    .string "¡Ya no tengo tanta sed!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "Mi hermana es ENTRENADORA,\n"
    .string "¡de verdad!\p"
    .string "¡Pero es tan infantil que me vuelve\n"
    .string "loco!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "¡Tengo sed!\n"
    .string "¡Me gustaría beber algo!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "ÚLTIMO PISO:\n"
    .string "DISTRIBUIDORES$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "¡Un distribuidor!\n"
    .string "¡A ver el menú!$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "¡Vaya, no tengo suficiente dinero!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "¡Una lata de {STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "¡No tienes sitio para más cosas!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "¡No tengo sed!$"
