Text_MetronomeTeach::
    .string "¡Tac-tac-tac! Voy a enseñarte\n"
    .string "un movimiento estupendo.\p"
    .string "Enséñaselo a un POKéMON,\n"
    .string "verás qué guay es.\p"
    .string "Se llama METRÓNOMO, no me\n"
    .string "digas que no suena bien...$"

Text_MetronomeDeclined::
    .string "Te lo digo, es el no va más.$"

Text_MetronomeWhichMon::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe METRÓNOMO?$"

Text_MetronomeTaught::
    .string "¡Tac-tac-tac!\n"
    .string "¡Ése es el sonido de un METRÓNOMO!\p"
    .string "¡Lleva al POKéMON a usar ataques\n"
    .string "que no conoce!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "¡Hola!\p"
    .string "¡Soy un científico muy importante!\n"
    .string "Mucho, sí, sí.\p"
    .string "¡Y me dedico a estudiar fósiles\n"
    .string "de POKéMON raros!\p"
    .string "¿Tienes algún fósil para mí?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "¡No!\n"
    .string "¡Qué pena!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "¿Dónde estabas?\p"
    .string "¡Tu fósil ha revivido!\n"
    .string "¡Sabía que era un {STR_VAR_1}!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "¡{PLAYER} recibió {STR_VAR_1}\n"
    .string "de manos del científico!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "¡Oh! ¡Es un {STR_VAR_2}!\p"
    .string "¡Es un fósil de {STR_VAR_1},\n"
    .string "un POKéMON ya extinto!\p"
    .string "¡Mi máquina recuperadora\n"
    .string "hará que este POKéMON reviva!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "¡Date prisa y dame eso!\p"
#ifdef BUGFIX
    .string "{COLOR DARK_GRAY}¡{PLAYER} le dio {STR_VAR_2}\n"
#else
    .string "{FONT_NORMAL}¡{PLAYER} le dio {STR_VAR_2}\n"
#endif
    .string "al extraño científico!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "¡Tardaré un poco!\p"
    .string "¡Date un paseo mientras tanto!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "¡Eh!\n"
    .string "¡Has venido a molestarme!$"
