MtMoon_B2F_Text_MiguelIntro::
    .string "¡No toques nada!\p"
    .string "¡Yo encontré estos fósiles!\n"
    .string "¡Son míos!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "¡De acuerdo!\n"
    .string "¡Los compartiré!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "¡Uno para cada!\n"
    .string "¡No hay que ser avaricioso!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "Muy bien.\n"
    .string "¡Pues éste es el mío!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Muy lejos, en ISLA CANELA, hay\n"
    .string "un LABORATORIO de POKéMON.\p"
    .string "En él estudian cómo regenerar\n"
    .string "los fósiles de POKéMON.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "El TEAM ROCKET encontrará\n"
    .string "los fósiles, los revivirá ¡y los\l"
    .string "venderá!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "¡Argh!\n"
    .string "¡Eres lo peor!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "¡Eres un fastidio! ¡El TEAM ROCKET\n"
    .string "te pondrá en la lista negra!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "¡Nosotros, el TEAM ROCKET,\n"
    .string "somos los bandidos POKéMON!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "¡Lo he hecho fatal!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "¿Será posible?\n"
    .string "¡Mis compañeros me vengarán!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "¡Nuestro trabajo aquí es muy\n"
    .string "importante! ¡Lárgate, enclenque!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "Pues eres muy fuerte...$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Si encuentras un fósil, ¡dámelo\n"
    .string "y lárgate!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "¡Los niños no deberían molestar\n"
    .string "a los adultos!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "¡Estoy muy enfadado!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "Los POKéMON vivían aquí mucho\n"
    .string "antes de que llegara la gente.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "¿Quieres el FÓSIL DOMO?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "¿Quieres el FÓSIL HELIX?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "¡Obtuviste el FÓSIL HELIX!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "¡Obtuviste el FÓSIL DOMO!$"

MtMoon_B2F_Text_FoundBuriedFossil::
    .string "Entre las rocas hay algo enterrado...\p"
    .string "¡Es el otro fósil de MT. MOON!$"
