SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENTE: ¡Gracias por salvar\n"
    .string "a SILPH!\p"
    .string "¡Jamás olvidaré que nos salvaste\n"
    .string "en este peligroso momento!\p"
    .string "¡Me gustaría agradecértelo\n"
    .string "de alguna forma!\p"
    .string "¡Yo puedo darte muchas cosas!\p"
    .string "¡Toma, puede que te interese!$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENTE: ¡Gracias por salvar\n"
    .string "a SILPH!\p"
    .string "¡Jamás olvidaré que nos salvaste\n"
    .string "en este peligroso momento!\p"
    .string "¡Me gustaría agradecértelo\n"
    .string "de alguna forma!\p"
    .string "¡Yo puedo darte muchas cosas!\p"
    .string "¡Toma, puede que te interese!$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "¡{PLAYER} recibió una MASTER\n"
    .string "BALL del PRESIDENTE!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENTE: ¡No puedes comprarla\n"
    .string "en ningún sitio!\p"
    .string "¡Es nuestro prototipo secreto\n"
    .string "de la MASTER BALL!\p"
    .string "¡Puede atrapar a cualquier tipo\n"
    .string "de POKéMON!\p"
    .string "Pero mejor que no se lo digas\n"
    .string "a nadie.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "No tienes sitio para esto.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARIA: ¡Gracias por\n"
    .string "salvarnos!\p"
    .string "Todos los que trabajamos para el\n"
    .string "PRESIDENTE admiramos tu valor.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Otra vez tú, {PLAYER}.\p"
    .string "El PRESIDENTE de SILPH y yo\ntenemos asuntos pendientes.\p"
    .string "No pienso permitir que\ninterfieras por segunda vez.\p"
    .string "¡Conocerás el poder\ndel TEAM ROCKET!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "¿Otra vez derrotado...?\n¡Esto no puede ser!$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "Has frustrado mi operación\nen SILPH S. A.\p"
    .string "Pero no confundas una\nderrota con el final.\p"
    .string "El TEAM ROCKET seguirá\nadelante mientras yo lo dirija.\p"
    .string "Recuerda mi nombre, {PLAYER}.\nVolveremos a vernos.$"

SilphCo_11F_Text_Grunt2Intro::
    .string "¡Alto ahí!\n"
    .string "¡No te muevas!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "No...\n"
    .string "¡Por favor!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "¿¡Qué!?\n"
    .string "¿Quieres ver a mi JEFE?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "¡Alto!\n"
    .string "¿Tienes una cita con mi JEFE?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "¡Auch!\n"
    .string "¡Me han derribado!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Ten cuidado, ¡Los POKéMON\n"
    .string "de mi JEFE son terribles!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "¡Hay un POKéMON en el monitor!$"

SilphCo_11F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P10$"
