PokemonMansion_Text_PressSecretSwitch::
    .string "Un botón secreto.\p"
    .string "¿Lo pulso?$"

PokemonMansion_Text_WhoWouldnt::
    .string "¿Y quién no lo haría?$"

PokemonMansion_Text_NotQuiteYet::
    .string "¡Todavía no!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "¡No sé salir! ¡Este viejo lugar\n"
    .string "es un enorme laberinto!$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "¡Oh, no!\n"
    .string "¡Mi botín!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "¡Los botones abren y cierran\n"
    .string "alternativamente los grupos\l"
    .string "de puertas!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Diario: 5 de julio.\n"
    .string "Guyana, Suramérica.\p"
    .string "Un nuevo tipo de POKéMON fue\n"
    .string "descubierto en el interior de la\l"
    .string "selva.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Diario: 10 de julio.\n"
    .string "Hemos llamado a este nuevo\l"
    .string "POKéMON, MEW.$"


PokemonMansion_2F_Text_FullMewSighting2::
    .string "¡Miiiu!\p"
    .string "Algo se asoma junto al viejo diario\n"
    .string "y desaparece antes de que puedas\l"
    .string "acercarte.$"
