CinnabarIsland_Gym_Text_BlaineIntro::
    .string "¡Ja, ja! ¡Soy BLAINE,\nLÍDER del GIMNASIO de CANELA!\p"
    .string "¡Pregunta de examen!\n¿Qué arde más que una llama?\p"
    .string "¡Mi pasión por los POKéMON!\n¡Prepárate para combatir!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "¡Ja! ¡Me has dejado sin llama!\p"
    .string "Pero no sin admiración.\n¡La MEDALLA VOLCÁN es tuya!$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "¡LLAMARADA golpea con fuerza!\p"
    .string "Pero ni siquiera el fuego\nvence a todos los tipos.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "¡Ja!\p"
    .string "¡La MEDALLA VOLCÁN mejora las\n"
    .string "habilidades ESPECIALES de tus\l"
    .string "POKéMON!\p"
    .string "¡Mira, también te daré esto!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "¡{PLAYER} recibió la MT38\n"
    .string "de manos de BLAINE!$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "¡LLAMARADA exige decisión!\p"
    .string "Hasta el fuego más potente\nfracasa sin buena estrategia.\p"
    .string "¡Entrena y haz que arda\ntu espíritu competitivo!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "¡Ja! ¡No cabe ni una chispa!\nHaz sitio en tu mochila.$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "¿Sabes el calor que puede dar el\n"
    .string "aliento de fuego de un POKéMON?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "¡Ay!\n"
    .string "¡Quema, quema!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Fuego o, para ser más preciso,\n"
    .string "combustión...\p"
    .string "¡Bla, bla, bla, bla!...$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "Yo era ladrón, pero me hice\n"
    .string "honrado cuando me convertí\l"
    .string "en ENTRENADOR.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "¡Me rindo!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "¡No puedo evitar robar los POKéMON\n"
    .string "de otras personas!$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "¡No puedes ganar!\n"
    .string "¡Soy un experto en POKéMON!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "¡Au!\n"
    .string "¡Tanta teoría para nada!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "¡Mis teorías son muy complicadas\n"
    .string "para ti!$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "¡Me encanta usar POKéMON\n"
    .string "del tipo FUEGO!$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "¡No hay quien pueda contigo!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "¡Ojalá hubiera un POKéMON ladrón!\n"
    .string "¡Me encantaría utilizarlo!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "¡Ya sé por qué BLAINE se hizo\n"
    .string "ENTRENADOR!$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "¡Auuuuuuuuuu!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "BLAINE se perdió en la montaña,\n"
    .string "y se hizo de noche...\p"
    .string "¡Pero apareció un feroz pájaro\n"
    .string "POKéMON...!\p"
    .string "¡E iluminó el camino a BLAINE\n"
    .string "para que pudiera bajar!$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "¡He estado en muchos GIMNASIOS,\n"
    .string "pero éste es mi preferido!$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "¡Vaya!\n"
    .string "¡Eso quema!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "¡A nosotros, los seguidores de los\n"
    .string "POKéMON de fuego, nos gustan\l"
    .string "PONYTA y NINETALES!$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "El fuego es débil contra el H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "¡Oh!\n"
    .string "¡Esto se acabó!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "¡El agua apaga el fuego!\p"
    .string "¡Pero el fuego derrite a los\n"
    .string "POKéMON de hielo!$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "¡Hola, aspirante al título!\p"
    .string "¡BLAINE es un profesional\n"
    .string "de los POKéMON de fuego!\p"
    .string "¡Bájale los humos con agua!\p"
    .string "¡Más vale que lleves\n"
    .string "ANTIQUEMAR!$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "¡{PLAYER}, has ganado a esa\n"
    .string "antorcha con patas!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CANELA: BLAINE\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CANELA: BLAINE\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "¡POKéACERTIJO!\p"
    .string "¡Responde bien y abrirás la puerta\n"
    .string "a la siguiente habitación!\p"
    .string "¡Responde mal y lucharás contra\n"
    .string "un ENTRENADOR!\p"
    .string "Si prefieres reservar tus POKéMON\n"
    .string "para el LÍDER del GIMNASIO...\p"
    .string "¡Hazlo bien!\n"
    .string "¡Vamos allá!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "¿Evoluciona CATERPIE y\n"
    .string "se transforma en METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "¿Hay 9 MEDALLAS oficiales\n"
    .string "de la LIGA POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "¿Evoluciona POLIWAG 3 veces?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "¿Afectan los movimientos del tipo\n"
    .string "ELÉCTRICO a los POKéMON\l"
    .string "del tipo TIERRA?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "¿Son distintos los POKéMON del\n"
    .string "mismo tipo y del mismo nivel?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "¿Contiene la MT28 TUMBAPIEDRA?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "¡Respuesta correcta!\p"
    .string "¡Adelante!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "¡Mal!\n"
    .string "¡Lo siento!$"
