FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Eh... Ah, hola.\n"
    .string "Durante años fui investigador\n"
    .string "de la ZONA SAFARI.\p"
    .string "Aprendí que algunas especies\n"
    .string "no permanecen en una sola región.\p"
    .string "Una vez hallé tres rastros\n"
    .string "distintos, llegados desde JOHTO:\l"
    .string "agua, relámpago y fuego.\p"
    .string "Intenté seguirlos, pero se\n"
    .string "esfumaban en un instante.\p"
    .string "Desde entonces sé que algunos\n"
    .string "POKéMON recorren el mundo entero.$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "¿Qué POKéMON debería olvidar\n"
    .string "algún movimiento?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "¿Qué movimiento debería olvidar?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "Parece que {STR_VAR_1} sólo sabe\n"
    .string "un movimiento...$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Ajá.\n"
    .string "¿{STR_VAR_2} de {STR_VAR_1}?\l"
    .string "¿Ése quieres? ¿De verdad?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "¡Ha salido de perlas!\p"
    .string "{STR_VAR_1} ha olvidado\n"
    .string "completamente {STR_VAR_2}.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Vuelve por aquí si quieres que tus\n"
    .string "POKéMON olviden algún movimiento.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "¿Cómo? Un HUEVO no puede saber\n"
    .string "ningún movimiento.$"
