Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "El PROFESOR me pidió premiar a\n"
    .string "Entrenadores que progresen.\p"
    .string "Me encargó darte REPARTIR EXP.\n"
    .string "si ya tienes la MEDALLA ARCOIRIS.\p"
    .string "¿Ya tienes la MEDALLA ARCOIRIS?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "¡Perfecto! Esa MEDALLA demuestra\n"
    .string "cuánto has avanzado.\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route15_WestEntrance_2F_Text_NeedRainbowBadge::
    .string "Vuelve cuando consigas la\n"
    .string "MEDALLA ARCOIRIS.\p"
    .string "Guardaré REPARTIR EXP. para ti.$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "¡{PLAYER} obtuvo {STR_VAR_2}\n"
    .string "de manos del AYUDANTE!$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "REPARTIR EXP. es un objeto\n"
    .string "que puede llevar un POKéMON.\p"
    .string "Dará puntos de EXPERIENCIA\n"
    .string "al POKéMON que lo lleve, aunque\l"
    .string "no luche.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "Has usado los prismáticos...\p"
    .string "Un pájaro grande y brillante vuela\n"
    .string "hacia el mar.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "Has usado los prismáticos...\p"
    .string "¡Parece que hay una pequeña isla!$"
