FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "En esta isla nació y creció una\n"
    .string "ENTRENADORA fuerte y poderosa\l"
    .string "como pocas.\p"
    .string "Seguro que la conoces, se llama\n"
    .string "PRIMA y es del ALTO MANDO.\p"
    .string "Yo le enseñé muchas cosas sobre\n"
    .string "los POKéMON cuando aún era un\l"
    .string "comino.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "En realidad, ARCHI7 está\n"
    .string "en una zona cálida.\p"
    .string "Pero hay una excepción de la que\n"
    .string "quiero hablarte.\p"
    .string "La CUEVA GLACIADA es un lugar\n"
    .string "frío por el POKéMON que la habita.$"
