TwoIsland_House_Text_MoveReminderIntro::
	.string "Ich bin der ATTACKEN-MANIAC!\p"
	.string "Ich kann einem POKéMON eine\n"
	.string "vergessene Attacke beibringen.\p"
	.string "Jede Lektion kostet 2000.$"

TwoIsland_House_Text_NotEnoughMoney::
	.string "Du hast nicht genug Geld.\p"
	.string "Eine Lektion kostet 2000.$"

TwoIsland_House_Text_PaidForMove::
	.string "{PLAYER} zahlt 2000 für die Lektion.$"

TwoIsland_House_Text_TeachMonMoveForMushroom::
	.string "Ich bin der POKéMON-ATTACKEN-\n"
	.string "MANIAC!\p"
	.string "Ich kenne jede Attacke, die\n"
	.string "POKéMON beim Levelanstieg\l"
	.string "erlernen.\l"
	.string "Ich bin auch ein Pilzsammler.\p"
	.string "Gib mir zwei MINIPILZE oder\n"
	.string "einen RIESENPILZ.\p"
	.string "Dafür bringe ich einem deiner\n"
	.string "POKéMON eine Attacke bei.$"

TwoIsland_House_Text_WantMeToTeachMove::
	.string "Schnief, schnief…\n"
	.string "Hm! Du riechst nach PILZEN!\p"
	.string "Soll ich einem deiner POKéMON\n"
	.string "eine Attacke beibringen?$"

TwoIsland_House_Text_TutorWhichMon::
	.string "Welches POKéMON soll sie lernen?$"

TwoIsland_House_Text_TeachWhichMove::
	.string "Welche Attacke soll ich es lehren?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
	.string "Tut mir Leid...\p"
	.string "Scheinbar gibt es keine Attacke,\n"
	.string "die ich diesem POKéMON beibringen\l"
	.string "kann.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
	.string "Gib mir einen oder zwei PILZE!\n"
	.string "Was willst du mir geben?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
	.string "{PLAYER} übergibt zwei\n"
	.string "MINIPILZE.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
	.string "{PLAYER} übergibt einen\n"
	.string "RIESENPILZ.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
	.string "Falls deine POKéMON eine\n"
	.string "Attacke lernen sollen, musst du\l"
	.string "mir einen oder zwei PILZE geben!$"

TwoIsland_House_Text_CantTeachAnEgg::
	.string "Bitte? Ich kann einem EI nicht eine\n"
	.string "einzige Attacke beibringen!$"

