TwoIsland_House_Text_MoveReminderIntro::
	.string "Je suis le DINGUE DES CAPACITES.\p"
	.string "Je peux rappeler à un POKéMON\n"
	.string "une capacité qu'il a oubliée.\p"
	.string "Chaque leçon coûte 2000.$"

TwoIsland_House_Text_NotEnoughMoney::
	.string "Tu n'as pas assez d'argent.\p"
	.string "Une leçon coûte 2000.$"

TwoIsland_House_Text_PaidForMove::
	.string "{PLAYER} paie 2000 pour la leçon.$"

TwoIsland_House_Text_TeachMonMoveForMushroom::
	.string "Je suis le DINGUE DES CAPACITES.\p"
	.string "Je connais chaque capacité que\n"
	.string "les POKéMON peuvent apprendre.\p"
	.string "J'adore aussi les champignons.\p"
	.string "Ramène-moi deux PETITS CHAMPIS\n"
	.string "ou un gros CHAMPI.\p"
	.string "Si tu fais ça, j'apprendrai une\n"
	.string "capacité à un POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
	.string "Sniff, sniff…\n"
	.string "Hum, ça sent les CHAMPIS!\p"
	.string "Tu veux que j'enseigne une\n"
	.string "capacité à un de tes POKéMON?$"

TwoIsland_House_Text_TutorWhichMon::
	.string "Quel POKéMON choisis-tu?$"

TwoIsland_House_Text_TeachWhichMove::
	.string "Quelle attaque dois-je enseigner?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
	.string "Désolé…\p"
	.string "Apparemment, il n'y a aucune\n"
	.string "attaque que je puisse apprendre à\l"
	.string "ce POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
	.string "Alors j'aurais besoin d'un ou deux\n"
	.string "CHAMPIS. Qu'est-ce que tu as?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
	.string "{PLAYER} donne deux PETITS CHAMPIS\n"
	.string "en échange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
	.string "{PLAYER} donne un GROS CHAMPI en\n"
	.string "échange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
	.string "Si tu veux que j'enseigne une\n"
	.string "attaque à ton POKéMON, reviens\l"
	.string "avec un champignon ou deux.$"

TwoIsland_House_Text_CantTeachAnEgg::
	.string "Quoi? Mais je ne peux pas\n"
	.string "apprendre une attaque à un OEUF.$"

