TwoIsland_House_Text_MoveReminderIntro::
    .string "Soy el TUTOR de MOVIMIENTOS.\p"
    .string "Puedo hacer que un POKéMON recuerde\n"
    .string "un movimiento que haya olvidado.\p"
    .string "Cada lección cuesta 2000.$"

TwoIsland_House_Text_NotEnoughMoney::
    .string "No tienes suficiente dinero.\p"
    .string "Una lección cuesta 2000.$"

TwoIsland_House_Text_PaidForMove::
    .string "{PLAYER} pagó 2000 por la lección.$"

TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Soy el TUTOR de MOVIMIENTOS.\p"
    .string "Me sé todos los movimientos que\n"
    .string "aprenden los POKéMON. Todos,\l"
    .string "toditos, todos. Y puedo enseñar.\p"
    .string "También soy EXPERTO en SETAS.\p"
    .string "Si me traes dos MINI SETAS o una\n"
    .string "SETA GRANDE, le enseñaré un\l"
    .string "movimiento a uno de tus POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Sniff, sniff...\n"
    .string "¡Mmm! ¡Hueles a SETA!\p"
    .string "¿Quieres que le enseñe un\n"
    .string "movimiento a uno de tus POKéMON?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "¿Qué POKéMON quieres que lo\n"
    .string "aprenda?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "¿Qué movimiento quieres que\n"
    .string "aprenda?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Perdona...\p"
    .string "Parece que no puedo enseñar ningún\n"
    .string "movimiento a ese POKéMON...$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Pues tendrás que darme una SETA\n"
    .string "o un par de ellas.\l"
    .string "¿Qué me das?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} entregó dos MINI SETAS\n"
    .string "a cambio de la lección.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} entregó una SETA GRANDE\n"
    .string "a cambio de la lección.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Si quieres que le enseñe un\n"
    .string "movimiento a algún POKéMON,\l"
    .string "tráeme una SETA o dos.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "¿Eh? No puedo enseñar\n"
    .string "absolutamente ningún movimiento\l"
    .string "a un HUEVO...$"
