TwoIsland_House_Text_MoveReminderIntro::
    .string "Sono l'ESPERTO MOSSE!\p"
    .string "Posso far ricordare a un POKéMON\n"
    .string "una mossa che ha dimenticato.\p"
    .string "Ogni lezione costa 2000.$"

TwoIsland_House_Text_NotEnoughMoney::
    .string "Non hai abbastanza denaro.\p"
    .string "Una lezione costa 2000.$"

TwoIsland_House_Text_PaidForMove::
    .string "{PLAYER} paga 2000 per la lezione.$"

TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Ciao, sono l'ESPERTO MOSSE!\p"
    .string "Conosco ogni singola mossa dei\n"
    .string "POKéMON.\p"
    .string "Sono anche un appassionato di\n"
    .string "funghi.\p"
    .string "Portami due MINIFUNGHI o un\n"
    .string "GRANDE FUNGO.\p"
    .string "In cambio, insegnerò una mossa\n"
    .string "ad uno dei tuoi POKéMON!$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Sniff sniff sniff…\p"
    .string "Hai dei FUNGHI, vero?\n"
    .string "Sento il profumo!\p"
    .string "Vuoi che insegni una mossa ad\n"
    .string "uno dei tuoi POKéMON?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Che POKéMON vuoi istruire?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Che mossa devo insegnargli?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Sono spiacente…\p"
    .string "Non credo di avere alcuna mossa da\n"
    .string "insegnare a quel POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Beh, avrei bisogno di uno o due\n"
    .string "FUNGHI. Cosa puoi darmi?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} gli dà in cambio\n"
    .string "due MINIFUNGHI.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} gli dà in cambio\n"
    .string "un GRANDE FUNGO.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Se vuoi che insegni una mossa ai\n"
    .string "tuoi POKéMON, devi darmi uno\l"
    .string "o due FUNGHI.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Eh? Non conosco alcuna mossa per\n"
    .string "quell'UOVO.$"

