Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
	.string "The types of POKéMON match up\n"
	.string "differently with each other.\p"
	.string "Every type is stronger than some\n"
	.string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
	.string "A NUGGET is totally useless.\n"
	.string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
	.string "I heard that ghosts haunt\n"
	.string "LAVENDER TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
	.string "Oh… {PLAYER}!\n"
	.string "I've been looking for you!\p"
	.string "It's me, one of PROF. OAK's AIDES.\p"
	.string "He entrusted me with this EVERSTONE\n"
	.string "for Trainers making good progress.\p"
	.string "If you've earned the THUNDER BADGE,\n"
	.string "this reward is yours.\p"
	.string "Have you earned the THUNDER BADGE?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
	.string "Great! That BADGE shows how far\n"
	.string "you've come as a Trainer.\p"
	.string "Congratulations!\n"
	.string "Here you go!$"

Route10_PokemonCenter_1F_Text_NeedThunderBadge::
	.string "Come back after you've earned the\n"
	.string "THUNDER BADGE.\p"
	.string "I'll keep the EVERSTONE safe for you.$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
	.string "{PLAYER} received the EVERSTONE\n"
	.string "from the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
	.string "Making POKéMON evolve certainly\n"
	.string "can add to the POKéDEX.\p"
	.string "However, at times, you may not\n"
	.string "want a certain POKéMON to evolve.\p"
	.string "In that case, give the EVERSTONE\n"
	.string "to that POKéMON.\p"
	.string "It will prevent evolution according\n"
	.string "to the PROFESSOR.$"
