Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "¡Los POKéMON de ciertos elementos\n"
    .string "son más o menos fuertes que otros!$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "¡Vendí una inútil PEPITA\n"
    .string "por 5.000¥!$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "¡Dicen que hay fantasmas en\n"
    .string "PUEBLO LAVANDA!$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "El PROFESOR me pidió premiar a\n"
    .string "Entrenadores que progresen.\p"
    .string "Me encargó darte la PIEDRAETERNA\n"
    .string "si ya tienes la MEDALLA TRUENO.\p"
    .string "¿Ya tienes la MEDALLA TRUENO?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "¡Perfecto! Esa MEDALLA demuestra\n"
    .string "cuánto has avanzado.\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route10_PokemonCenter_1F_Text_NeedThunderBadge::
    .string "Vuelve cuando consigas la\n"
    .string "MEDALLA TRUENO.\p"
    .string "Guardaré la PIEDRAETERNA para ti.$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "¡{PLAYER} obtuvo la\n"
    .string "PIEDRAETERNA de manos\l"
    .string "del AYUDANTE!$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "Si dejas evolucionar a los\n"
    .string "POKéMON, tu POKéDEX\l"
    .string "se verá beneficiada.\p"
    .string "Aunque habrá algún caso en el\n"
    .string "que no quieras que evolucionen.\p"
    .string "Para evitarlo, dale al POKéMON\n"
    .string "que quieras una PIEDRAETERNA.\p"
    .string "Según dice el PROFESOR,\n"
    .string "el POKéMON que la lleve,\l"
    .string "no evolucionará.$"
