Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "El PROFESOR me pidió premiar a\n"
    .string "Entrenadores que progresen.\p"
    .string "Me encargó darte el BUSCAOBJETOS\n"
    .string "si ya tienes la MEDALLA TRUENO.\p"
    .string "¿Ya tienes la MEDALLA TRUENO?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "¡Perfecto! Esa MEDALLA demuestra\n"
    .string "cuánto has avanzado.\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"

Route11_EastEntrance_2F_Text_NeedThunderBadge::
    .string "Vuelve cuando consigas la\n"
    .string "MEDALLA TRUENO.\p"
    .string "Guardaré el BUSCAOBJETOS para ti.$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "¡{PLAYER} obtuvo {STR_VAR_2}\n"
    .string "de manos del AYUDANTE!$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "En el suelo hay objetos que no se\n"
    .string "pueden ver.\p"
    .string "El BUSCAOBJETOS detectará\n"
    .string "los objetos que tengas cerca.\p"
    .string "¡Pero no puede señalar dónde están\n"
    .string "exactamente!\p"
    .string "¡Tú tendrás que encontrarlos!$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Has usado los prismáticos...\p"
    .string "¡Un gran POKéMON está durmiendo\n"
    .string "en el camino!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Has usado los prismáticos...\p"
    .string "¡Qué vista tan bonita!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Has usado los prismáticos...\p"
    .string "¡Puedes ir de CIUDAD CELESTE\n"
    .string "a PUEBLO LAVANDA por el TÚNEL\l"
    .string "ROCA!$"
