VermilionCity_Gym_Text_LtSurgeIntro::
    .string "¡ALTO, soldado! Soy LT. SURGE.\p"
    .string "En combate aprendí que un\ninstante decide una victoria.\p"
    .string "Mis POKéMON ELÉCTRICOS\nparalizarán tus planes.\p"
    .string "¡Prepárate para la descarga!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "Ni un ejército de rayos puede\ncon un buen POKéMON TIERRA.\p"
    .string "Recuerda: conoce el terreno\nantes de entrar en combate.$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "¡La MEDALLA TRUENO aumenta la\n"
    .string "VELOCIDAD de tus POKéMON!\p"
    .string "¡Y permite volar a tus POKéMON\n"
    .string "cuando quieran!\p"
    .string "¡Tú eres muy especial!\n"
    .string "¡Toma esto!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "¡{PLAYER} recibió la MT34\n"
    .string "de manos de LT. SURGE!$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "La MT34 contiene ONDA VOLTIO.\p"
    .string "Es un ataque ELÉCTRICO que\nno falla. ¡Úsalo con cabeza!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "¡Mochila llena, soldado!\n¡Despeja el equipo y vuelve!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "¡Buen trabajo, soldado!\p"
    .string "Has resistido mi ofensiva.\n¡La MEDALLA TRUENO es tuya!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "¡Cuando estaba en el ejército,\n"
    .string "el LT. SURGE era muy estricto!$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "¡Alto!\n"
    .string "¡Eres genial!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "No es fácil abrir esta puerta...\p"
    .string "¡El LT. SURGE siempre fue muy\n"
    .string "cauteloso en el ejército!$"

VermilionCity_Gym_Text_BailyIntro::
    .string "¡No es que yo sea muy fuerte,\n"
    .string "pero soy muy bueno con la\l"
    .string "electricidad!$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "¡Qué paliza!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "¡Vale, hablaré!\p"
    .string "¡LT. SURGE dijo que ocultaría los\n"
    .string "botones de la puerta dentro de\l"
    .string "algo!$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "¡Este lugar no es para niños!\n"
    .string "¡Por muy fuerte que seas!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "¡Uuuaa!\n"
    .string "¡Me dejas a cuadros!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE colocó cerraduras\n"
    .string "dobles en el GIMNASIO.\p"
    .string "¡Las puso por todos sitios!\n"
    .string "¡Te daré una pista!\p"
    .string "¡Tras abrir la 1.ª cerradura, la\n"
    .string "2.ª está al lado!$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "¡Hola, aspirante al título!\p"
    .string "El LT. SURGE tiene un mote. La\n"
    .string "gente le llama: ¡Rayo americano!\p"
    .string "¡Es un experto en POKéMON\n"
    .string "eléctricos!\p"
    .string "¡Los POKéMON voladores y los\n"
    .string "acuáticos están en peligro! ¡Ten\l"
    .string "cuidado con la parálisis!\p"
    .string "¡El LT. SURGE es muy cuidadoso!\p"
    .string "¡Descifra un código y llegarás a\n"
    .string "él!$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "¡Uau!\n"
    .string "¡Vaya pelea tan eléctrica!$"

VermilionCity_Gym_Text_GymStatue::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "¡No, aquí sólo hay basura!$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "¡Oye! ¡Hay un botón debajo de la\n"
    .string "basura!\p"
    .string "¡Púlsalo!\n"
    .string "Abierto primer cierre eléctrico.$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "Abierto segundo cierre eléctrico.\p"
    .string "¡Abierta la puerta mecánica!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "¡No! Aquí sólo hay basura.\p"
    .string "¡Las cerraduras eléctricas fueron\n"
    .string "reajustadas!$"
