ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "PEDRITA: Buuuua... ¡BUAAAA!...\n"
    .string "¡Ayúdame, ayúdame!\p"
    .string "POKéMON ho-horrible...\n"
    .string "Mmme he sustado ucho...\p"
    .string "Buaaaaa... Sustado a PEDRITA...\p"
    .string "Teno miedo...\n"
    .string "Quiedo id a casa...$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "¡Ta ahí, ta ahí!\n"
    .string "¡Fuela, fuela! ¡Teno miedo!\p"
    .string "¡Buaaaaaaaaa!\n"
    .string "¡Papiiiiiiiiii!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Aaaah... POKéMON malo...\n"
    .string "¡Acias!\p"
    .string "PEDRITA quedía BAYAS.\p"
    .string "Toma, cara ti.$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "¿Quién ede?\p"
    .string "PEDRITA sustada, lleva a casa\n"
    .string "con papi a PEDRITA.\p"
    .string "¡A casa con papi!\n"
    .string "¡Con papi!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "El SACO de las BAYAS está lleno.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Éste es el BOSQUE BAYA.\p"
    .string "¡Hay que compartir BAYAS\n"
    .string "con la gente y los POKéMON!$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Atención:\n"
    .string "Presencia de POKéMON salvajes\l"
    .string "devoradores de BAYAS.$"


ThreeIsland_BerryForest_Text_FullCelebiAppears::
    .string "Las hojas comienzan a agitarse sin\n"
    .string "que sople viento alguno...\p"
    .string "Una luz verde rodea el árbol.\p"
    .string "¡CELEBI ha aparecido!$"
