ThreeIsland_BerryForest_Text_HelpScaryPokemon::
	.string "IRRMA: Wimmer… schnief…\n"
	.string "Oh! Hilf mir bitte!\p"
	.string "Ein Angst einflößendes POKéMON ist\n"
	.string "dort vor kurzem aufgetaucht.\p"
	.string "Es war so gruselig.\n"
	.string "Es hat IRRMA Angst gemacht.\p"
	.string "Ich bin zu verängstigt, um mich\n"
	.string "zu bewegen! Aber ich möchte\l"
	.string "nach Hause gehen…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
	.string "Oh! Hier ist es wieder! Nein!\n"
	.string "Verschwinde! Es macht mir Angst!\p"
	.string "Wahhhhhhhhhhh!\n"
	.string "Ich will zu meinem Papa!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
	.string "Oh! Das war so gruselig!\n"
	.string "Dankeschön!\p"
	.string "IRRMA wollte hier BEEREN\n"
	.string "pflücken.\p"
	.string "Das ist für dich!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
	.string "Wie heißt du?\p"
	.string "IRRMA ist so verängstigt!\n"
	.string "Bringst du mich nach Hause?\p"
	.string "O.K.!\n"
	.string "Lass uns nach Hause gehen!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
	.string "Deine BEERENTÜTE ist voll.\n"
	.string "Ich denke, du willst das nicht.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
	.string "Willkommen im BEERENFORST!\p"
	.string "Sei freundlich und teile die BEEREN\n"
	.string "mit Anderen und POKéMON!$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
	.string "Nimm dich vor wilden POKéMON,\n"
	.string "die BEEREN lieben, in Acht!$"

ThreeIsland_BerryForest_Text_FullCelebiClue1::
    .string "A recent note has been added:\p"
    .string "BERRIES ripen out of season, and some\n"
    .string "POKéMON return as if time repeated.\p"
    .string "There may be another clue near the\n"
    .string "BERRY FOREST entrance.$"

ThreeIsland_BerryForest_Text_FullCelebiClue2::
    .string "Another observation was added:\p"
    .string "The green light always gathers around\n"
    .string "one unusual tree.\p"
    .string "It may be worth checking the forest trees.$"

