ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LISETTA: Aiuto! Aiuto!\p"
    .string "Prima è arrivato un POKéMON\n"
    .string "spaventoso!\p"
    .string "Ora ho tanta paura che non posso\n"
    .string "muovermi! Ma voglio andare a casa!$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Ecco! Ritorna!\n"
    .string "No! No! Via! Via!\p"
    .string "Voglio il mio papino!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Grazie! Mi hai salvata!\p"
    .string "Stavo cercando BACCHE.\p"
    .string "Ecco, prendi!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "Come ti chiami?\p"
    .string "Ho ancora paura! Puoi\n"
    .string "accompagnarmi dal mio papino?\p"
    .string "Grazie!\n"
    .string "LISETTA torna a casa!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Il PORTABACCHE è pieno.\n"
    .string "Non posso darti il mio regalo.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Benvenuti nel BOSCO\n"
    .string "BACCOSO!\p"
    .string "Condividete le BACCHE con i\n"
    .string "POKéMON e gli altri ALLENATORI!$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Guardati dai POKéMON selvatici\n"
    .string "ghiotti di BACCHE!$"

ThreeIsland_BerryForest_Text_FullCelebiClue1::
    .string "A recent note has been added:\p"
    .string "BERRIES ripen out of season, and some\n"
    .string "POKéMON return as if time repeated.\p"
    .string "There may be another clue near the\n"
    .string "BERRY FOREST entrance.$"

ThreeIsland_BerryForest_Text_FullCelebiClue2::
    .string "Another observation was added:\p"
    .string "The green light always gathers around\n"
    .string "one unusual tree.\p"
    .string "It may be worth checking the forest trees.$"

